### ISSUE TITLE
1.0.30 java.lang.IllegalStateException: Failed to introspect annotated methods on class reactivefeign.spring.config.ReactiveFeignClientsConfiguration

### ISSUE THREAD

**Issue by kongh** [Playtika/feign-reactive#107]
java.lang.IllegalStateException: Failed to introspect annotated methods on class reactivefeign.spring.config.ReactiveFeignClientsConfiguration

upgrade your sample project version to 1.0.30, after starting feign, you can see this error

**Comment by kptfh** [comment]
fixed in 1.0.44
