### ISSUE TITLE
Multipart/Formdata

### ISSUE THREAD

**Issue by msektrier** [Playtika/feign-reactive#114]
Many thanks for developing this library. We are glad to be able to use it! 
However, we are facing some issues with multipart/formdata when we passthrough it with feign-reactive. 

Our webflux controller at endpoint 1 has a simple interface 
```
@PutMapping(value = User.UPDATE, consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public Mono<> method(@RequestPart("files") Flux<Part> files) 
```

and receives incoming multipart formdata as a stream. If we now store the files directly we have no issues. But we do not know at the moment how to pass it to another internal webservice via feign-reactive. 

Our feign interface in endpoint 1 looks like 

```
  @RequestLine("POST " + Document.BASE)
  @Headers({"Accept: application/json", "Content-Type: multipart/form-data"})
  public Flux<DataDTO> createDocument(@RequestBody Flux<Part> files);
```

Most of the time we receive this error message before sending anything via feign-reactive

> "Content type 'multipart/form-data' not supported for bodyType=org.springframework.http.codec.multipart.Part"

The error message sounds quite odd and any help or idea is very appreciated.

**Comment by kptfh** [comment]
waiting for pr https://github.com/spring-projects/spring-framework/pull/24535 to be merged

**Comment by jonathannaguin** [comment]
Is there another way of accomplishing this? It seems the Spring merge is waiting and likely, it will take time until they finally merge into a version.

**Comment by kptfh** [comment]
As workaround you can copy-paste formatter from the PR and configure your Spring context to use it. There definitely should be the way to do it.

**Comment by jonathannaguin** [comment]
Thanks @kptfh! I also realised I could use MultiValueMap which is already supported by Spring:

```
Mono<Reply> upload(MultiValueMap<String, ?> files)
```

For building this map, I use MultipartBodyBuilder.

**Comment by kptfh** [comment]
yes (as workaround only)  but it will need to load content of all files into memory.
The formatter from PR should allow to avoid it. It will stream content of files without loading

**Comment by rmalyona** [comment]
Hey @kptfh Is anything blocks the PR from merging?
