### ISSUE TITLE
ResponseEntity Support

### ISSUE THREAD

**Issue by gmcouto** [Playtika/feign-reactive#209]
Hello,

I have a client like this that I'm trying to make it work using reactive feign.
```
@ReactiveFeignClient(name = "mktcloud-service", url = "http://localhost:8092")
public interface JourneyV1Client {
  @RequestMapping(
      value = "/v1/journeys/apikey",
      produces = {"application/json"},
      method = RequestMethod.GET)
  Mono<ResponseEntity<ApiKeySearchResponseDTO>> findApiKey(
      @NotNull
          @ApiParam(value = "Journey Name", required = true)
          @Valid
          @RequestParam(value = "name", required = true)
          String name);
}
```

However when I run the application I face the following issue:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.http.ResponseEntity` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1589) ~[jackson-databind-2.10.2.jar:2.10.2]
```

On regular feign there is the Encoder and Decoder concept, and spring implementation of openfeign uses a ResponseEntityDecoder to wrap the other decoders.

I did not see a similar way to perform this on reactive feign, so I think this must be an issue, as Spring support seems to be part of the project.

**Comment by kptfh** [comment]
Hi, @gmcouto .
Why do you need this? 
BTW: There is no commitment to support all Spring features. The basic goal of this project to help developers write effective and clean code.

**Comment by gmcouto** [comment]
It is mainly because we are using OpenAPI-generator to generate all the interfaces on an API-first application as part of the build process.
As the interface generator for spling-cloud includes ResponseEntity, and it is supported by OpenFeign, I thought it would be useful to have it here... so the client can use the same API interface we use for controllers.

**Comment by kptfh** [comment]
Here is the example

**Comment by gmcouto** [comment]
Thanks, sorry for not answering before.

I was thinking on something like this:

https://github.com/gmcouto/feign-reactive/commit/42211aa95efaa95d23087dc83abebaead019c65f

So it is transparent to the application. That is the version we are using to have this support.

Can I open a Merge Request?

**Comment by kptfh** [comment]
It

**Comment by gmcouto** [comment]
Actually the interface openapi is generator is generating this return type:
`Mono<ResponseEntity<ApiKeySearchResponseDTO>>`

Which was causing the errors described in the original post. The PR works for it, which is the fix we are using in our codebase.

**Comment by kptfh** [comment]
It's not reactive. Reactive version is Mono<ResponseEntity<Mono/Flux<ApiKeySearchResponseDTO>>>

**Comment by kptfh** [comment]
Can you customize openapi-generator to generate API in form `Mono<ReactiveHttpResponse<Mono<ApiKeySearchResponseDTO>>>`  ?

**Comment by gmcouto** [comment]
Why is that not reactive? It is an implementation of WebClientUtils, uses WebClient for the request (supposed to be reactive), returns a Mono, and no single `.block()` is called in the process.
Sorry, I`m new to reactive in Java so I may be missing something.

**Comment by kptfh** [comment]
`Mono<ReactiveHttpResponse<Mono<ApiKeySearchResponseDTO>>>` allows you to subscribe on response, read headers and drop body if needed. In your case body will be always deserialized.
`Mono<ReactiveHttpResponse<Flux<ApiKeySearchResponseDTO>>>` allows to subscribe to result and process flux of elements. And if you need omit rest of elements at some points. In your case all elements will be deserialized. I think that spring should fix their implementation to support `ResponseEntity<Mono/Flux<R>>` .

**Comment by gmcouto** [comment]
I get it now, and that is a good point.

I think however, for the exception of lists, anyone using feign does intend to deserialize the whole body all the time. Which is what I have changed, and is working for us.

Anyway, I will investigate if it is too much on an effort to make our controllers work with ReactiveHttpResponse and change open-api, because, ideally, I wanted to use the same interface in both sides(controller/client) auto-generated, for consistency. It is beginning to seem like a luxury though.

**Comment by kptfh** [comment]
As I see, ideally to ask Spring to support `Mono<ResponseEntity<Mono<ApiKeySearchResponseDTO>>>`

**Comment by kptfh** [comment]
I have even prepared the fix on reactive feign side but it fails when I call `toEntity(ParameterizedTypeReference<Mono<ApiKeySearchResponseDTO>>)`

**Comment by kptfh** [comment]
fixed 
here is the example [Mono<ResponseEntity<Flux<Integer>>> call()](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-webclient/src/test/java/reactivefeign/webclient/ResponseEntityTest.java#L54)

**Comment by gerardbosch** [comment]
Hello @kptfh , I think when you say

> ideally to ask Spring to support Mono<ResponseEntity<Mono<ApiKeySearchResponseDTO>>>

you actually mean https://github.com/OpenAPITools/openapi-generator instead of Spring ;)
I've added some comments into this, backing your arguments to support it in that way: https://github.com/OpenAPITools/openapi-generator/issues/1309#issuecomment-673163349

Cheers!

**Comment by hamza-maqsood** [comment]
I have something like this: Mono<ResponseEntity<Flux<InvoiceResponse>>>
The way I am processing the request is something as follows:
val response = serviceClient.request().awaitFirstOrNul()
if(response.isSuccessful()) {
  val invoices = response.body.collectList()?.awaitFirstOrNull()
}

but the following exception is being rasied
java.lang.IllegalStateException: Only one connection receive subscriber allowed.
