### ISSUE TITLE
Client Specific RequestInterceptor / OAuth?

### ISSUE THREAD

**Issue by SledgeHammer01** [Playtika/feign-reactive#211]
Can you provide an example of how to have a PER CLIENT ReactiveHttpRequestInterceptor while still maintaining the ability to connect by service name? I've tried both WebReactiveFeign.builder() and CloudReactiveFeign.builder() and they can connect by URL only. If I use @EnableReactiveFeignClients, then it works by service name, but I can only add a global ReactiveHttpRequestInterceptor and have no way knowing which Oauth details to use.

**Comment by kptfh** [comment]
You can have separate configuration for each feign client.
You can find example in this test
[ReactiveFeignClientUsingConfigurationsTests](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-test/src/test/java/reactivefeign/spring/config/ReactiveFeignClientUsingConfigurationsTests.java)

**Comment by kptfh** [comment]
If you need dynamic request interceptor that will be able to set headers based on the request parameters then you can use this pattern (even with configuration)
```
ReactiveFeignBuilder
    .addRequestInterceptor(request -> Mono
            .subscriberContext()
            .map(ctx -> ctx
                    .<String>getOrEmpty("authToken")
                    .map(authToken -> {
                        Map<String, List<String>> headers = new LinkedHashMap<>(request.headers());
                        headers.put("Authorization", List.of(authToken));
                        return new ReactiveHttpRequest(request.method(), request.uri(), headers, request.body());
                    })
                    .orElse(request));)
```

**Comment by SledgeHammer01** [comment]
> You can have separate configuration for each feign client.
> You can find example in this test
> [ReactiveFeignClientUsingConfigurationsTests](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-test/src/test/java/reactivefeign/spring/config/ReactiveFeignClientUsingConfigurationsTests.java)

@kptfh

Hi Sergii, I followed the model in the test:

xxxFeignClient.java -> @ReactiveFeignClient(name="xxx", configuration=xxxFeignClientConfig1.class)

yyyFeignClient.java -> @ReactiveFeignClient(name="yyy", configuration=yyyFeignClientConfig2.class)

In xxxFeignClientConfig1, I have a bean:

	@Bean
	public ReactiveHttpRequestInterceptor r1() {
		return new ReactiveHttpRequestInterceptor() {

			@Override
			public Mono<ReactiveHttpRequest> apply(ReactiveHttpRequest t) {
				System.out.println("xxx");
				t.headers().put("Authorization", Arrays.asList("Bearer xxx"));
				return Mono.just(t);
			}
		};
	}

In xxxFeignClientConfig2, I have a bean:

	@Bean
	public ReactiveHttpRequestInterceptor r2() {
		return new ReactiveHttpRequestInterceptor() {

			@Override
			public Mono<ReactiveHttpRequest> apply(ReactiveHttpRequest t) {
				System.out.println("yyy");
				t.headers().put("Authorization", Arrays.asList("Bearer yyy"));
				return Mono.just(t);
			}
		};
	}

When I run, during the xxx test I get output:

xxx
yyy

During the yyy test I get output:

yyy
xxx

So it seems to be using both beans on both clients. Is that the expected behavior? I can check to see if the header is already there as a work-around, but it seems like adding unneeded overhead, unless I am missing something?

I did see with the builders, I can specifically specify an interceptor so only one gets added, but its not clear how to build a client that can use http://MYSERVICE style urls.

Is there an existing mechanism for OAuth or do we need to implement one from scratch? I see this uses WebClient under the covers, there is an out of the box filter function for WebClient for oauth (ServerOAuth2AuthorizedClientExchangeFilterFunction / AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager), but there doesn't seem to be a way to connect that.

Thanks again!
