### ISSUE TITLE
Console app hangs with Cloud2 / ReactiveLoadBalancer

### ISSUE THREAD

**Issue by SledgeHammer01** [Playtika/feign-reactive#213]
Hi,

I am trying to use cloud2 and my app is hanging on exit. Not sure if this is here or spring-cloud reactive load balancer yet.  This is a console app, so it runs, does its thing and exits. I can't use the starter directly, since I need to customize the WebClient.  Here is how I am initializing:

Windows 10 Pro x64
Spring Boot 2.2.6
JDK 11.0.6

Gradle looks like:

	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:2.2.2.RELEASE'
	implementation 'com.playtika.reactivefeign:feign-reactor-webclient:2.0.2'
	implementation 'com.playtika.reactivefeign:feign-reactor-cloud2:2.0.2'
	implementation 'com.playtika.reactivefeign:feign-reactor-spring-configuration:2.0.2'

Code wise, I am using the CloudReactiveFeign builder:

```
		ReactiveFeignNamedContext namedContext = new ReactiveFeignNamedContext(this.applicationContext, name);

		ReactiveLoadBalancer.Factory<ServiceInstance> loadBalancerFactory
		= namedContext.get(ReactiveLoadBalancer.Factory.class);
		
		ReactiveFeignBuilder<T> builder = CloudReactiveFeign.<T>builder(WebReactiveFeign.builder(
			WebClient.builder()
				.filter(filterFunction(name.toLowerCase())))).enableLoadBalancer(loadBalancerFactory);

		List<AbstractReactiveFeignConfigurator> configurators = new ArrayList<>(
			namedContext.getAll(AbstractReactiveFeignConfigurator.class).values());

		Collections.sort(configurators);

		for (AbstractReactiveFeignConfigurator configurator : configurators)
			configurator.configure(builder, namedContext);

		return builder
			.target(clazz, name, "http://" + name);

```

Can you provide any insight? P.S. for cloud v1, the app exists, but throws an illegal state exception on the netflix ShutdownTimerEnabled Shutdown In Progress.

Thanks!

**Comment by SledgeHammer01** [comment]
some additional findings:

1) if I change the last line to localhost:8080 but still leave the enableLoadBalancer call, then it doesn't hang.
2) if I leave as localhost:8080, leave the enableLoadBalancer call AND also call the factory.getInstance() to try to use the LB, it also doesn't hang. Just when I let reactive-feign use it internally.

**Comment by kptfh** [comment]
@SledgeHammer01 If you use absolute url (like  localhost:8080) then loadbalancer is not used. 
Seems that some internal load balancer thread prevent you app from closing. Try to print out all active threads while closing your app.

**Comment by SledgeHammer01** [comment]
> @SledgeHammer01 If you use absolute url (like localhost:8080) then loadbalancer is not used.
> Seems that some internal load balancer thread prevent you app from closing. Try to print out all active threads while closing your app.

Yes, I understand absolute doesn't use the LB. It was for testing to isolate to the load balancer. I ran the app in debug mode and viewed the threads:

* bunch of Deamon threads for reactor-http-nio
* 1 for DiscoveryClient-CacheRefreshExecutor
* 1 for DiscoveryClient-HeartBeatExecutor
* 1 regular thread for DestroyJavaVM
* 1 threadpool still running named pool-1-thread-1.

**Comment by SledgeHammer01** [comment]
@kptfh 

> If you use absolute url (like localhost:8080) then loadbalancer is not used.
> Seems that some internal load balancer thread prevent you app from closing. Try to print out all active threads while closing your app.

Yes, I understand absolute doesn't use the LB. It was for testing to isolate to the load balancer. I ran the app in debug mode and viewed the threads:

bunch of Deamon threads for reactor-http-nio
1 for DiscoveryClient-CacheRefreshExecutor
1 for DiscoveryClient-HeartBeatExecutor
1 regular thread for DestroyJavaVM
1 threadpool still running named pool-1-thread-1.

**Comment by kptfh** [comment]
Try to find a way how to close DiscoveryClient

**Comment by kptfh** [comment]
Closed due to inactivity
