### ISSUE TITLE
Spring feign-reactor-cloud2 timeout

### ISSUE THREAD

**Issue by howardem** [Playtika/feign-reactive#215]
Hi everyone,

We are using the Spring cloud module through feign-reactor-cloud2 + spring-cloud-starter-circuitbreaker-reactor-resilience4j (Ribbon and Hystrix are disabled) and everything works fine except for the timeout configurations. Could someone provide me with an example with the proper way to override the default 1s read timeout per Feign client?

Thanks

**Comment by kptfh** [comment]
Hi. There are two places for timeout configuration - http client and circuitbreaker:
Regarding Resilience4j: 
[Global customization](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-cloud2-test/src/test/java/reactivefeign/spring/config/cloud2/AutoConfigurationTest.java#L179)
[Specific feign client customization](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-cloud2-test/src/test/java/reactivefeign/spring/config/cloud2/AutoConfigurationTest.java#L188)

**Comment by kptfh** [comment]
[If you want configure feign client manually](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-cloud2/src/test/java/reactivefeign/cloud2/BuilderUtils.java#L48)

**Comment by renecairo** [comment]
Thanh you! @kptfh 
Works like a charm!

**Comment by Yordanyspd** [comment]
Thanks, your solution is great.

**Comment by howardem** [comment]
Thanks so much!! We have been using your library since its early release and now are doing some major refactoring and moving to the newest **feign-reactor-cloud2**.  Your library should be included as part of the Spring Cloud project.

CC: @spencergibb, @ryanjbaxter

**Comment by vasilievip** [comment]
@howardem  https://github.com/spring-cloud/spring-cloud-openfeign/issues/4#issuecomment-585875126
