### ISSUE TITLE
@Param not working in @Header annotation

### ISSUE THREAD

**Issue by oemergenc** [Playtika/feign-reactive#223]
Hi,

i am trying to port a traditional `FeignClient` to a `ReactiveFeignClient` in my project. Here is my interface definition:
```
@ReactiveFeignClient(name = "my-client",
        url = "\${my.url}",
        configuration = [MyConfig::class])
interface MyReactiveClient {

    @RequestLine("POST /the/post/url")
    @Headers("Authorization: Bearer {token}", "Content-Type: application/json")
    fun predict(@Param("token") token: String, myRequest: MyRequest): Mono<MyResponse>
}
```
While this works for a traditional `FeignClient` there seems to be a problem with the `token` parameter in the reactive implementation. The parameter does not get set on the header. Is there anything wrong with this approach?

**Comment by kptfh** [comment]
As workaround you may try to pass  "Bearer "+token together as header param value.
Here is the working example [Header param](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-core/src/test/java/reactivefeign/allfeatures/AllFeaturesFeign.java#L68)

**Comment by oemergenc** [comment]
Hi, 

thanks for the quick response. Indeed this fixed the header issue. Unfortunately i am running into another problem now:

```
14:18:58.233 [http-nio-auto-1-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] threw exception
org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'application/octet-stream' not supported for bodyType=com.my.domain.MyResponse	at org.springframework.web.reactive.function.BodyExtractors.lambda$readWithMessageReaders$12(BodyExtractors.java:201)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Body from  [DefaultClientResponse]
....
```
It seems that the `"Content-Type: application/json"`header is being ignored, although explicitly set in the header annotation?

Maybe you could also help me with this?

**Comment by kptfh** [comment]
Do you mean that response has header "Content-Type: application/json" and it's ignored?

**Comment by oemergenc** [comment]
As far as i can see the problem comes from here:

https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/function/BodyExtractors.java#L189-L190

It seems that `message.getHeaders().getContentType()` returns `null` and therefore the fallback is used. During debugging i can see that `message.getRequestHeaders`  has the correct content-type being set. I am clueless, the response should be correctly formatted as i am using a mock server which worked without problems using the traditional FeignClient.

**Comment by oemergenc** [comment]
I am still stuck with this, any idea would be greatly appreciated.

**Comment by kptfh** [comment]
Good starting point of investigation is to fork project and add your test
(that cover your case) beside those I provided above.  After that I will be
able to help you.

**Comment by oemergenc** [comment]
Hey, thanks for your help. I was able to resolve this problem. The problem was that the mock server did not explicitly set the content-type. In this case the reactive implementation falls back to `application/octet-stream` while the classical feign-client seems to fallback to `application/json`.
