### ISSUE TITLE
Supports custom pojo to query param mapping

### ISSUE THREAD

**Issue by Ivanbmstu** [Playtika/feign-reactive#227]
Hello,
Have you any plans to add such feature to reactive feign like pojo mapping to query parameters https://github.com/OpenFeign/feign#dynamic-query-parameters ? Or "welcome to contribute"?

**Comment by kptfh** [comment]
It's a good feature. Will consider introducing it in reactive feign

**Comment by Ivanbmstu** [comment]
I can try backport it from feign similar to https://github.com/OpenFeign/feign/blob/9f21dcc8c85285f176c88212b5813bd355fec2ec/core/src/main/java/feign/ReflectiveFeign.java#L249-L258

**Comment by kptfh** [comment]
released in 2.0.6
