### ISSUE TITLE
The fuse exhausts all threads

### ISSUE THREAD

**Issue by lhtGit** [Playtika/feign-reactive#233]
Sending more than 10 Feign requests in one request will cause the fuse to exhaust all threads, resulting in only 10 request results being returned, how can I avoid it

**Comment by lhtGit** [comment]
Use version 1.0.30

**Comment by huahouye** [comment]
Did you use Hystix as a circuitbreaker? If so, you can take a closer look at [Netflix/Hystrix/wiki/Configuration#ThreadPool](https://github.com/Netflix/Hystrix/wiki/Configuration#ThreadPool)

**Comment by lhtGit** [comment]
Thank you for your answer, it reminds me
