### ISSUE TITLE
Using reactive feign client to read response headers

### ISSUE THREAD

**Issue by marcbarb** [Playtika/feign-reactive#240]
I am trying to use the Playtika reactive feign client to do a non blocking read from a service and read the response headers. I can get all this to work fine with regular feign clients, but when going to reactive, I don't know how to decode the response to get at the headers. Using a Mono doesn't seem to work. I get a:

Caused by: org.springframework.web.reactive.function.UnsupportedMediaTypeException: Content type 'text/plain;charset=UTF-8' not supported for bodyType=feign.Response

error. Here is my source code. Any ideas?:

```
@SpringBootApplication
@EnableEurekaClient
@RestController
@EnableReactiveFeignClients
@EnableFeignClients
public class FeignApplication implements CommandLineRunner {

    @Autowired
    private GreetingReactive reactiveFeignClient;

    public static void main(String[] args) {
        SpringApplication.run(FeignApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {

        Mono<Response> a = reactiveFeignClient.greetingWithParam("a");
        a.subscribe(response ->
                System.out.println(response.headers().get("sessionId").iterator().next()),
                    doe->e.printStackTrace());
        while (true);
    }
}


@ReactiveFeignClient(name = "web-flux-app")
public interface GreetingReactive {

    @GetMapping("/greeting")
    Mono<String> greeting();

    @GetMapping(value = "/greetingWithParam")
    Mono<Response> greetingWithParam(@RequestParam(value = "id") String id);
}
```

**Comment by kptfh** [comment]
You should use Spring's ResponseEntity or feign's ReactiveHttpResponse 
Here is the  [example for WebClient based Feign client](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-webclient/src/test/java/reactivefeign/webclient/ResponseEntityTest.java)
And  [more general approach](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-core/src/test/java/reactivefeign/SmokeTest.java#L210)

**Comment by marcbarb** [comment]
Thanks this works when using the latest version of the software.  I was trying to use the feign-reactive-sample code which is at 1.0.44 and doesn't work to decode ResponseEntities.  I see this capability was just recently added.

You may want to update the sample code to work with the latest software.

I'm fine for this issue to be closed.
