### ISSUE TITLE
IllegalArgumentException on using MicrometerReactiveLogger

### ISSUE THREAD

**Issue by warmuuh** [Playtika/feign-reactive#248]
i use this micrometerReactiveLogger configuration:
`new MicrometerReactiveLogger(
          Clock.systemUTC(),
          meterRegistry,
          CLIENT_CALL_METRIC_NAME,
          Set.of(MetricsTag.FEIGN_CLIENT_METHOD,
              MetricsTag.URI_TEMPLATE,
              MetricsTag.HTTP_METHOD,
              MetricsTag.STATUS,
              MetricsTag.EXCEPTION));
}`
but because there are exceptions only on some calls, the exception tag is not always present, which results in this exception from prometheus side:
```
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'http_client_requests_seconds' containing tag keys [feignMethod, method, status, uri]. The meter you are attempting to register has keys [exception, feignMethod, method, status, uri].
```
there should maybe be the EXCEPTION tag always present, defaulting to "none" for example

**Comment by kptfh** [comment]
fixed in 2.0.7
