### ISSUE TITLE
Memory Leak if decode404

### ISSUE THREAD

**Issue by warmuuh** [Playtika/feign-reactive#251]
I am currently hunting a memory leak and while debugging, i saw that, if the WebReactiveFeign sets `decode404()` then `org.springframework.core.io.buffer.DataBufferUtils#release` is never called. I am still not sure, but i believe that this causes a memory leak. have to dig into that deeper to actually find the regarding code in feign-reactive though, but maybe you have an idea already

**Comment by kptfh** [comment]
@warmuuh  Thank you for this catch. 
Fixed in 2.0.8.
Please check it from your side
