### ISSUE TITLE
Two way SSL with configuration file

### ISSUE THREAD

**Issue by marcbarb** [Playtika/feign-reactive#253]
I am trying to write a Reactive Feign webclient that uses two-way SSL sending a client certificate to the server for authentication.  The following code which uses code similar to [TrustingSSLSocketFactory](https://github.com/OpenFeign/feign/blob/master/core/src/test/java/feign/client/TrustingSSLSocketFactory.java) works for a regular feign client, but reactive doesn't seem to call the execute method of Client.Default which sets up the SSLContext.  This results in a bad certificate error.  Any ideas what I'm doing wrong?  You can use the code at https://www.baeldung.com/x-509-authentication-in-spring-security to set up the server I am testing with.

```
@ReactiveFeignClient(name = "web-flux-app", configuration = Conf.class
        , url = "https://localhost:8443")
public interface TestClient {

    @GetMapping(value = "/user", produces = "text/html")
    Mono<String> root();
```
```
@Configuration
@Slf4j
public class Conf {

    @Bean
    public Client feignClient() throws NoSuchAlgorithmException {

        SSLSocketFactory ssl = TrustingSSLSocketFactory.get(
                "clientbob");
        Client client = new Client.Default(ssl, new NoopHostnameVerifier());
        log.info("called feign client");
        return client;
    }
}
```
    @Autowired
    private TestClient testClient;

        String block = testClient.root()
                .block();
        System.out.println(block);
```

**Comment by kptfh** [comment]
Have you checked if WebClient supports this feature?
Default implementation of ReaciveFeign fully relies on WebClient networking features

**Comment by marcbarb** [comment]
This code works with WebClient.  I'm not sure how it maps to using ReactiveFeign with a configuration.

```
String keyStoreLocation = System.getProperty("javax.net.ssl.keyStore");
String keyStorePassword = System.getProperty("javax.net.ssl.keyStorePassword");

KeyStore keyStore = KeyStore.getInstance("JKS");
keyStore.load(new FileInputStream(ResourceUtils.getFile(keyStoreLocation)), keyStorePassword.toCharArray());

// Set up key manager factory to use our key store
KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
keyManagerFactory.init(keyStore, keyStorePassword.toCharArray());

String block = WebClient.builder()
        .clientConnector(new ReactorClientHttpConnector(
                HttpClient.create()
                        .secure(spec -> spec.sslContext(SslContextBuilder.forClient()
                                .keyManager(keyManagerFactory)))))
        .build()
        .get()
        .uri("https://localhost:8443/user")
        .retrieve()
        .bodyToMono(String.class)
        .block();
```

**Comment by kptfh** [comment]
If you build ReactiveFeign  client manually try to configure it this way
https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-webclient/src/main/java/reactivefeign/webclient/WebReactiveFeign.java#L33

**Comment by kptfh** [comment]
In case of auto-configuration try to define `WebClientFeignCustomizer' bean in client's scope
https://github.com/Playtika/feign-reactive/blob/bafb08f33142e494829b638d3bdfe3f30419ba29/feign-reactor-test/feign-reactor-spring-configuration-test/src/test/java/reactivefeign/spring/config/AutoConfigurationTest.java#L180

**Comment by marcbarb** [comment]
Great, thanks!  This works with the following configuration class, and I'm fine with closing this:

```
@Configuration
@Slf4j
public class Conf {

    @Bean
    public WebClientFeignCustomizer webClientCustomizer() throws KeyStoreException, IOException, NoSuchAlgorithmException, UnrecoverableKeyException, CertificateException {

        String keyStoreLocation = System.getProperty("javax.net.ssl.keyStore");
        String keyStorePassword = System.getProperty("javax.net.ssl.keyStorePassword");

        KeyStore keyStore = KeyStore.getInstance("JKS");
        keyStore.load(new FileInputStream(ResourceUtils.getFile(keyStoreLocation)), keyStorePassword.toCharArray());

        // Set up key manager factory to use our key store
        KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        keyManagerFactory.init(keyStore, keyStorePassword.toCharArray());

        return webClientBuilder -> webClientBuilder
                .clientConnector(new ReactorClientHttpConnector(
                        HttpClient.create()
                                .secure(spec -> spec.sslContext(SslContextBuilder.forClient()
                                        .keyManager(keyManagerFactory)))));
    }
```

**Comment by kptfh** [comment]
will add this into documentation

**Comment by kptfh** [comment]
don't forget to put a star :)
