### ISSUE TITLE
Does it support @SpringQueryMap

### ISSUE THREAD

**Issue by peacetrue** [Playtika/feign-reactive#258]
I tried it, does not seem to support @SpringQueryMap, same to PageableSpringEncoder.

**Comment by kptfh** [comment]
Here is the test that proves that reactive feign client supports `@SpringQueryMap`
[shouldReturnAllPassedParametersViaSpringQueryMap](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-mvc-test/src/test/java/reactivefeign/spring/mvc/allfeatures/AllFeaturesMvcTest.java#L74)

**Comment by peacetrue** [comment]
`@SpringQueryMap` is ok. Do you consider supporting `Pageable` and `Page`?

**Comment by kptfh** [comment]
Does open feign support this functionality?

**Comment by peacetrue** [comment]
@kptfh nonsupport, it is supported by spring.
