### ISSUE TITLE
Reactive Feign Client feign-core.jar incompatibility issue in contract class after version 2.0.0.

### ISSUE THREAD

**Issue by Boboi** [Playtika/feign-reactive#262]
Got the following Error Messages for the example in git hub,

An attempt was made to call a method that does not exist. The attempt was made from the following location:
    reactivefeign.ReactiveFeign.targetToHandlersByName(ReactiveFeign.java:106)
The following method did not exist:
    feign.Contract.parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List;
The method's class, feign.Contract, is available from the following locations:
    jar:file:/C:/Users/Bob/.m2/repository/io/github/openfeign/feign-core/10.4.0/feign-core-10.4.0.jar!/feign/Contract.class
It was loaded from the following location:
    file:/C:/Users/Bob/.m2/repository/io/github/openfeign/feign-core/10.4.0/feign-core-10.4.0.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of feign.Contract

pom.xml

 <properties>
               
        
        <feign-reactor.version>2.0.2</feign-reactor.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        

        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-webclient</artifactId>
            <version>${feign-reactor.version}</version>
        </dependency>

        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-cloud</artifactId>
            <version>${feign-reactor.version}</version>
        </dependency>

        <dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-spring-configuration</artifactId>
            <version>${feign-reactor.version}</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.feign</groupId>
            <artifactId>feign-slf4j</artifactId>
            <version>8.18.0</version>
            <exclusions>
            <exclusion>
            <groupId>com.netflix.feign</groupId>
            <artifactId>feign-core</artifactId>
            </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

example ->
//if you name feign client with eureka app name than you may omit ribbon configuration
@ReactiveFeignClient(name = "greeting-with-url", url = "localhost:8080")
public interface GreetingReactiveWithUrl {

    @GetMapping("/greeting")
    Mono<String> greeting();

    @GetMapping("/greetingWithParam")
    Mono<String> greetingWithParam(@RequestParam(value = "id") Long id);
    
    @GetMapping("/user")
    Mono<String> getUser(@RequestHeader(value = "id") String id);
}

**Comment by kptfh** [comment]
The latest version of library depends on  `<feign.version>10.10.1</feign.version>` and it has this method `feign.Contract.parseAndValidateMetadata`

This version goes from 
```
<groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-openfeign-dependencies</artifactId>
  <version>2.2.3.RELEASE</version>
```

So, try to update you dependency to `<feign.version>10.10.1</feign.version>`

**Comment by kptfh** [comment]
And don't forget to put star

**Comment by Boboi** [comment]
Ok, now it is working for latest feign-reactor JARs too by upgrading the version as you mentions and add one more dependency.

Following is working jar version in the pom.xml

Thank You!

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.3.RELEASE</version>
		<relativePath /> 
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>feign</artifactId>

	<properties>
	<feign-reactor.version>2.0.8</feign-reactor.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-openfeign-dependencies</artifactId>
			<version>2.2.3.RELEASE</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>


		<dependency>
			<groupId>com.playtika.reactivefeign</groupId>
			<artifactId>feign-reactor-webclient</artifactId>
			<version>${feign-reactor.version}</version>
		</dependency>

		<dependency>
			<groupId>com.playtika.reactivefeign</groupId>
			<artifactId>feign-reactor-cloud</artifactId>
			<version>${feign-reactor.version}</version>
		</dependency>

		<dependency>
			<groupId>com.playtika.reactivefeign</groupId>
			<artifactId>feign-reactor-spring-configuration</artifactId>
			<version>${feign-reactor.version}</version>
		</dependency>

		<dependency>
			<groupId>com.netflix.feign</groupId>
			<artifactId>feign-slf4j</artifactId>
			<version>8.18.0</version>
			<exclusions>
				<exclusion>
					<groupId>com.netflix.feign</groupId>
					<artifactId>feign-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-core</artifactId>
			<version>10.10.1</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-archaius</artifactId>
			<version>2.2.3.RELEASE</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
