### ISSUE TITLE
Circular bean dependency of ReactiveFeignCloudBuilder

### ISSUE THREAD

**Issue by MephistoLynn** [Playtika/feign-reactive#263]
I probably met the cycle dependencies situation.

Could you please help me check this problem ?

![微信截图_20200703150032](https://user-images.githubusercontent.com/22832393/86446546-af9ec600-bd46-11ea-84f9-03393f6c93e2.png)

And
> I have pushed my sample code that has the problem .
> When you feel free ,Could you please help me check the bug ? Thanks.
> [https://github.com/MephistoLynn/ReactiveFeignSample.git](url)

**Comment by kptfh** [comment]
It's difficult to investigate this issue without code that I can debug locally. 
Just try to update to the latest version.

**Comment by MephistoLynn** [comment]
> It's difficult to investigate this issue without code that I can debug locally.
> Just try to update to the latest version.

I have pushed my sample code with that problem .
When you feel free ,Could you please help me check the bug ? Thanks.
[https://github.com/MephistoLynn/ReactiveFeignSample](url)

**Comment by MephistoLynn** [comment]
Have the anybody ever met this problem ？

**Comment by tdanylchuk** [comment]
after clicking on repo you provided it leads me to 
![image](https://user-images.githubusercontent.com/3741358/86933410-809ea080-c108-11ea-8bdc-2d149b36b86e.png)
please check link correctness (maybe this is private repo)

**Comment by MephistoLynn** [comment]
> after clicking on repo you provided it leads me to
> ![image](https://user-images.githubusercontent.com/3741358/86933410-809ea080-c108-11ea-8bdc-2d149b36b86e.png)
> please check link correctness (maybe this is private repo)

Sorry about that.
I have corrected the url of my repo，please click this link.
Thank you so much !
[https://github.com/MephistoLynn/ReactiveFeignSample.git](https://github.com/MephistoLynn/ReactiveFeignSample.git)

**Comment by tdanylchuk** [comment]
So issue is that you have added feign cloud wrapper to your application, but actual feign client have not been added, so cloud feign tries to wrap itself.

Try to add ```implementation "com.playtika.reactivefeign:feign-reactor-webclient:${feignReactorVersion}"``` to your client and check if it will work for you.

As prevention option we might consider to add something like ```feign-reactor-spring-cloud-starter``` which will automatically include:
```feign-reactor-spring-configuration```
```feign-reactor-cloud```
```feign-reactor-webclient```

So you just need to add one deps, and free to go, @kptfh WDYT?
