### ISSUE TITLE
Add possibility to use generic response type - webclient

### ISSUE THREAD

**Issue by Gunthervg** [Playtika/feign-reactive#273]
Example:
```
@GetMapping()
<T> Mono<T> find();
```

In current implementation this will return an Map instead of the desired class.
I would suggest to add some sort of annotation:
```
@GetMapping()
<T> Mono<T> find(@GenericResponseType Class<T> responseClazz);
```

which then could be used by Jackson2Decoder to cast to correct class.

**Comment by kptfh** [comment]
It's better to use WebClient directly for this case. It allows to cast result to any type.
Feign client is used to enrich REST calls with API semantic  (return and parameter classes).
