### ISSUE TITLE
I can't discovery service in kubernets with loadbanlace?

### ISSUE THREAD

**Issue by flowclouds** [Playtika/feign-reactive#282]
when I use the reactiveFeign request the service ,the discovery doesn't build full ,the reactiveFeign just build mapping url,the service ip(ip:port) doesn,t build in the full url. how can i do that can let it work in kubernets environment?
the dependencies
![image](https://user-images.githubusercontent.com/40859714/89747565-ec9e6b00-daf1-11ea-9220-adbe33c17da2.png)
the reactiveFeign code
![image](https://user-images.githubusercontent.com/40859714/89747580-0049d180-daf2-11ea-98a2-39b3bd3d0b45.png)
the main application
![image](https://user-images.githubusercontent.com/40859714/89747589-0b046680-daf2-11ea-8280-39b60459e6ea.png)

**Comment by kptfh** [comment]
If you use @EnableDiscoveryClient annotation so you rely on discovery service. You should omit `url` parameter in `@ReactiveFeignClient`. Actual url will be resolved by service name from `name` parameter

**Comment by flowclouds** [comment]
thanks for ur answer. i have removed the url parameter ,but it likes cann't work discovery any service and threw a exception like this:
![image](https://user-images.githubusercontent.com/40859714/90108093-5c278b00-dd7c-11ea-9b53-01fde9afb2b2.png)

**Comment by kptfh** [comment]
You need to configure ribbon correctly
