### ISSUE TITLE
ReactiveRetryPolicies with resilience4j Circuit Breaker in HALF-OPEN state

### ISSUE THREAD

**Issue by dnguyen-gc** [Playtika/feign-reactive#283]
spring boot 2.3.2.RELEASE
spring cloud SR5
feign reactive 1.5.0
reactive cloud2

When the resilience4j circuit breaker is HALF-OPEN then how can I configure the retry so that it can retry the request? Or is it possible to configure the retry to work that way?  Here is my use-case:

I have 3 instances of the same service using reactive load balancer.  I DISABLED ribbon and hystrix so I can use RoundRobinLoadBalancer and resilience4j CB.

I configure the CB to transition very quickly (like 500 millis) from OPEN to HALF-OPEN as follow:
```
    @Bean
    public CircuitBreakerConfig circuitBreakerConfig() {
        return CircuitBreakerConfig.custom()
                .failureRateThreshold(50)
                .waitDurationInOpenState(Duration.ofMillis(500))
                .permittedNumberOfCallsInHalfOpenState(10)
                .automaticTransitionFromOpenToHalfOpenEnabled(true)
                .minimumNumberOfCalls(10)
                .recordExceptions(Exception.class)
                .build();
    }
```

I'd like to configure the retry using the next instance of the service.

For example below is my ReactiveRetryPolicies:
```
    @Bean
    public ReactiveRetryPolicies retryPolicies() {
        return new ReactiveRetryPolicies.Builder()
                .retryOnNext(retryWithBackoff(3, Duration.ofMillis(1000))).build();
    }
```

Once a request fails the CB should go into the Half-Open state then how can I configure retry to retry the request but using a different instance of the service.

Thank you.

**Comment by kptfh** [comment]
CB wraps LB.  
So if you configured LB to retry on next instance and it next instance of service returns result without error then CB will not open.

**Comment by dnguyen-gc** [comment]
@kptfh thank you!
