### ISSUE TITLE
MockBean not working with ReactiveFeignClient

### ISSUE THREAD

**Issue by NemesisMate** [Playtika/feign-reactive#287]
When using `@MockBean` in a test, the original feign client is not being replaced. This issue has already been addressed in spring cloud feign:

https://github.com/spring-cloud/spring-cloud-openfeign/issues/337
https://github.com/spring-cloud/spring-cloud-openfeign/commit/1929dae2d279bcb87e613a7663da4055baa9adb3

**Comment by kptfh** [comment]
fixed in 2.0.15
