### ISSUE TITLE
How get the body of Mono<ResponseEntity<Mono<String>>>

### ISSUE THREAD

**Issue by dnguyen-gc** [Playtika/feign-reactive#293]
Hello.
I have a rest controller defined as follow:
```
    @GetMapping("/testGet")
    public Mono<ResponseEntity<Mono<String>>> testGet() {
        Mono<ResponseEntity<Mono<String>>> f1 = Mono.zip(Mono.just("Hello"), Mono.just("World"))
                .map(t -> ResponseEntity.ok().body(Mono.just("All OK. Hello!")));
        return f1;
    }
```
Your test example uses StepVerifyer but it doesn't show the code on the client side that show how to actually read the body (string) from Mono<ResponseEntity<Mono<String>>>.  

```
        Mono<String> bodyMono = myFeignClient.testGet()
                .flatMap(response -> {

                    return Objects.requireNonNull(response.getBody())
                            .map(body -> {
                                return body;
                            });
                });
        bodyMono.subscribe();
```
But this doesn't work.

Please provide a sample client code.  Thank you.

**Comment by kptfh** [comment]
Do you have any stack trace?
Does error happen on server or client side?
Can you call this "get" just from browser to be sure that server works correctly?
