### ISSUE TITLE
Default Query Parameters and Headers for clients 

### ISSUE THREAD

**Issue by IlyasYOY** [Playtika/feign-reactive#311]
Recently I've proposed the same thing in OpenFeign.

Here is the PR https://github.com/spring-cloud/spring-cloud-openfeign/pull/420
And the issue https://github.com/spring-cloud/spring-cloud-openfeign/issues/284

I could port it in your project, what do you think of it?

Thanks for your work!

**Comment by kptfh** [comment]
Hi. Great idea!
Go ahead with implementation and pr

**Comment by IlyasYOY** [comment]
Firstly I'll add support for Headers from Config

Then I have to rewrite some parts of `reactivefeign.client.ReactiveHttpRequest`, because it doesn't allow me to specify URI and query parameters, how could I forget about this :sad:

**Comment by IlyasYOY** [comment]
Maybe be there are any pitfalls in ability to set Query params in interceptor?
