### ISSUE TITLE
Proper Proxy Configuration

### ISSUE THREAD

**Issue by cesardrk** [Playtika/feign-reactive#315]
My Project Setup :

- Spring Boot / Starter Webflux : 2.3.5.RELEASE
- Spring Cloud : Hoxton.SR8
- feign-reactor-spring-cloud-starter : 2.0.23

I need to use a corporate proxy for any non-local requests.
Adding configuration entries to JAVA_OPTS does not seem to have any effect (it does work with non-reactive stack):

```
-Djava.net.useSystemProxies=true
-Dhttp.proxyHost=myproxy.com
-Dhttp.proxyPort=80
-Dhttps.proxyHost=myproxy.com
-Dhttps.proxyPort=80
```

What is the proper way of configuring this?

**Comment by kptfh** [comment]
Google tells 
https://stackoverflow.com/questions/58689235/proxy-setting-not-working-with-spring-webclient/59640393#59640393

**Comment by cesardrk** [comment]
I saw that. I tried creating a bean for the ClientHttpConnector (ReactorClientHttpConnector) first and later feeding the WebReactiveFeign builder with my own WebClient.Builder with the former clientConnector, but neither worked. It seems to use another ClientHttpConnector from somewhere else.

**Comment by Viacheslav-Petriaiev** [comment]
Hi
I think I had a similar problem, webClient settings are lost.
WebReactiveFeighn builder has WebClientFeignCustomizer, so I've used it to set connector once again.
Maybe this code sample works for you:

```
        val connector: ClientHttpConnector = JettyClientHttpConnector(httpClient)

        val webClientBuilder = WebClient.builder()
                .clientConnector(connector)
                .codecs { configurer ->
                    configurer.registerDefaults(false)
                    configurer.customCodecs().register(Jackson2JsonEncoder(objectMapper, MediaType.APPLICATION_JSON))
                    configurer.customCodecs().register(Jackson2JsonDecoder(objectMapper, MediaType.APPLICATION_JSON))
                }

        val webReactiveFeignBuilder = WebReactiveFeign.builder<T>(webClientBuilder) { builder ->
            builder.clientConnector(connector)
        }
                .contract(contract)
                .statusHandler(errorDecoder)

```

**Comment by kptfh** [comment]
@Viacheslav-Petriaiev  this is the only one correct workaround solution. Will create to introduce proxy settings in ReactiveOptions class

**Comment by cesardrk** [comment]
Setting both the WebReactiveFeign and the WebClientFeignCustomizer builders with the connector did the trick.

**Comment by okysuryadi** [comment]
@cesardrk you can implement the WebClientFeignCustomizer class to solve this case

the following is an example that you might try :
> you can use ConfigurationProperties so that the configured values can be changed directly through the properties without having to change the source code (optional)
```
import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Data
@Configuration
@ConfigurationProperties(prefix = "proxy")
public class ProxyProperties {

  private boolean enabled;
  private String host;
  private int port;
  private String username;
  private String password;
  private long timeout;
}
```
> most importantly you need to implement the WebClientFeignCustomizer class, using ReactorClientHttpConnector and HttpClient
```
import lombok.RequiredArgsConstructor;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactivefeign.webclient.WebClientFeignCustomizer;
import reactor.netty.http.client.HttpClient;

import static reactor.netty.tcp.ProxyProvider.Proxy.HTTP;

@Component
@RequiredArgsConstructor
public class FeignInterceptor implements WebClientFeignCustomizer {

  private final ProxyProperties proxyProperties;

  @Override
  public void accept(WebClient.Builder builder) {
    if (proxyProperties.isEnabled()) {
      HttpClient httpClient = HttpClient.create()
          .tcpConfiguration(tcpClient -> tcpClient.proxy(typeSpec -> typeSpec.type(HTTP)
              .host(proxyProperties.getHost())
              .port(proxyProperties.getPort())
              .username(proxyProperties.getUsername())
              .password(password -> proxyProperties.getPassword())
              .connectTimeoutMillis(proxyProperties.getTimeout())
              .build()));

      builder.clientConnector(new ReactorClientHttpConnector(httpClient));
    }
  }
}
```

**Comment by jbaddam17** [comment]
How can i only override Timeout configuration for reactive feign client globally?
