### ISSUE TITLE
@ReactiveFeignClient adds path + "/" even if not necessary

### ISSUE THREAD

**Issue by islayeri** [Playtika/feign-reactive#332]
Copying issue from https://github.com/kptfh/feign-reactive/issues/13 as it is still reproducible. 

Final request path: ReactiveFeignClient.path + "/" + GetMapping.value
If GetMapping.value is default "/" is added anyway.
The behavior is different from FeignClient

Example:
`@GetMapping(produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
Result get(@RequestParam(value = "param") );`

`@ReactiveFeignClient(
path = "/my/path",
)`

Expected (non reactive feign-client behaviour):
`/my/path?param=...`
Real: additional '/' is added after ReactiveFeignClient.path
`/my/path/?param=...`

**Comment by rmatec** [comment]
Hi,

Thanks for fixing this. It was a show stopper for me. May I ask when you plan to release this fix?

**Comment by kptfh** [comment]
https://mvnrepository.com/artifact/com.playtika.reactivefeign/feign-reactor-core/2.0.26

**Comment by rmatec** [comment]
> https://mvnrepository.com/artifact/com.playtika.reactivefeign/feign-reactor-core/2.0.26

Thanks!
