### ISSUE TITLE
Manual initialization of  CloudReactiveFeign + Eureka + Ribbon + Hystrix

### ISSUE THREAD

**Issue by p4pramod** [Playtika/feign-reactive#333]
public interface GreetingReactive2 {
    @RequestLine("GET /greeting")
    Mono<String> greeting();
}

GreetingReactive2 client = CloudReactiveFeign.<GreetingReactive2>builder(WebReactiveFeign.builder())
        .enableLoadBalancer(s -> LoadBalancerCommand.builder()
                .withLoadBalancer(AbstractLoadBalancer.class.cast(getNamedLoadBalancer("greeting-other")))
                .withRetryHandler(new DefaultLoadBalancerRetryHandler(1, 1, true))
                .build())
        .target(GreetingReactive2.class, "http://" + "greeting-other");

client.greeting().subscribe()

application.yml

greeting-other:
  ribbon:
    # the eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: web-flux-app

I am not able to configure following line
   .withLoadBalancer(AbstractLoadBalancer.class.cast(getNamedLoadBalancer("greeting-other")))

Calling "client.greeting().subscribe()" throws timeout error. 

I spoilded whole day figuring out how to get ribbon loadbalanced instance to be passed to 

AbstractLoadBalancer.class.cast(getNamedLoadBalancer("greeting-other")) .

Please help.

**Comment by kptfh** [comment]
The latest version doesn't support Ribbon Load balancer
Check this functional test. You may use it as sample. 
https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-cloud/src/test/java/reactivefeign/cloud2/LoadBalancingReactiveHttpClientTest.java

Which version of library do you use?
