### ISSUE TITLE
New Feature Request: Support for @Param expander

### ISSUE THREAD

**Issue by davidmelia** [Playtika/feign-reactive#334]
Hi,

@Param has support for an expander which allows me to override the default ToString expander.  This means I can pass in microtypes into the API. i.e.

`
@RequestLine("GET /api/1/stuff/{agreementId}")
Mono<Something> getStuff(@Param(value = "agreementId", expander = AgreementIdExpander.class) final AgreementId agreementId)`

```
  final class AgreementIdExpander implements Expander {

    @Override
    public String expand(Object value) {
      return ((AgreementId) value).getValue();
    }
  }
```
Is this possible?

THANKS

**Comment by kptfh** [comment]
will create ticket
