### ISSUE TITLE
Cloud2 sample project.

### ISSUE THREAD

**Issue by p4pramod** [Playtika/feign-reactive#343]
The current sample project is not working with Cloud2. 

I am currently testing my code with playtika 2.0.26

**Comment by wohuizailai** [comment]
I'm writed a bolg on CSDN for reactive feign.[https://blog.csdn.net/LCBUSHIHAHA/article/details/113817966?spm=1001.2014.3001.5502](url)

**Comment by kptfh** [comment]
Updated https://github.com/kptfh/feign-reactive-sample to Cloud2
