### ISSUE TITLE
Support Spring @RequestAttribute annotation for declarative client params

### ISSUE THREAD

**Issue by vonZeppelin** [Playtika/feign-reactive#366]
Spring MVC has the `@RequestAttribute` annotation "to provide convenient access to request attributes ... with an optional/required check and a cast to the target method parameter type". `@RequestAttribute` annotation applied to parameters of a declarative client can be used to pass auxiliary data (e.g., AuthN/Z-related, tracing-related, etc.) to HTTP request interceptors without ever becoming a part of generated HTTP requests.

**Comment by kptfh** [comment]
Closed due to not supported by open feign client (blocking one)
