### ISSUE TITLE
Can you improve the document with README?

### ISSUE THREAD

**Issue by haycco** [Playtika/feign-reactive#37]
I use to feign-reactive ‘1.0.15‘ this version，when I using the readme example code and it not work.
```
/* Create instance of your API */
IcecreamServiceApi client = ReactiveFeign
    .builder()
    .target(IcecreamServiceApi.class, "http://www.icecreame.com")
...
```
ReactiveFeign API have modified, so that compile error.
Please, can you change the new version READEME content or provide another WIKI Website?
Hope to reply me,
Thanks...

**Comment by kptfh** [comment]
please, check it now.
