### ISSUE TITLE
how can I getInstance in  ReactiveFeign

### ISSUE THREAD

**Issue by ReeceZang** [Playtika/feign-reactive#382]
if (null == feignBuilder) {
            feignBuilder = getReactiveFeignBuilder();
        }
        return feignBuilder.build().newInstance(new Target.HardCodedTarget<>(clazz, aimUrl));
    }

**Comment by kptfh** [comment]
please check documentation and tests in this project

**Comment by ReeceZang** [comment]
How can i solve it
![image](https://user-images.githubusercontent.com/51372502/119474388-ac596200-bd7e-11eb-96be-3d4acc94678f.png)

**Comment by ReeceZang** [comment]
![image](https://user-images.githubusercontent.com/51372502/119803478-122a2300-bf12-11eb-89d6-a5ec37b6836b.png)
no conflicts ,  but still occurs 




An attempt was made to call a method that does not exist. The attempt was made from the following location:

    reactivefeign.ReactiveFeign.targetToHandlersByName(ReactiveFeign.java:104)

The following method did not exist:

    feign.Contract.parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List;

The method's class, feign.Contract, is available from the following locations:

    jar:file:/Users/zangjinrui/.m2/repository/io/github/openfeign/feign-core/10.2.4/feign-core-10.2.4.jar!/feign/Contract.class

It was loaded from the following location:

    file:/Users/zangjinrui/.m2/repository/io/github/openfeign/feign-core/10.2.4/feign-core-10.2.4.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of feign.Contract
