### ISSUE TITLE
PartHttpMessageWriter Not Found

### ISSUE THREAD

**Issue by alfikr** [Playtika/feign-reactive#392]
error on
java.lang.ClassNotFoundException: org.springframework.http.codec.multipart.PartHttpMessageWriter

what should i use in dependencies ?

**Comment by aboutZZ** [comment]
> Hi. If you use the latest version of reactive feign
> then you should use the following dependencies
> 
> ```
>             <dependency>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-dependencies</artifactId>
>                 <version>2.4.5</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> 
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>2020.0.2</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> ```

Im using gradle:
```
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		mavenBom "org.springframework.boot:spring-boot-dependencies:${springVersion}"
	}
}
```
But still getting this error.

**Comment by aboutZZ** [comment]
> Hi. If you use the latest version of reactive feign
> then you should use the following dependencies
> 
> ```
>             <dependency>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-dependencies</artifactId>
>                 <version>2.4.5</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> 
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>2020.0.2</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> ```

Which version should use for Springboot 2.3.x ?

**Comment by kptfh** [comment]
2.0.X
