### ISSUE TITLE
Adding Feign to the library for use without Spring

### ISSUE THREAD

**Issue by hurek** [Playtika/feign-reactive#401]
Hello. I am coding a reactive API library for the exchange, I want to find out if it is possible to use a reactive Feign as a dependency. I'm not sure that it will work without Spring, but I would like this version of my reactive client to be able to be used both in Spring applications and in regular Java applications. 

- Is it possible?
- Are there any features that I should take into account?
- And is reactive feign compatible with java8?

thanks for the answer!

**Comment by kptfh** [comment]
Hi. It's possible.
You should use **feign-reactor-jetty** or **feign-reactor-java11**

**Comment by hurek** [comment]
@kptfh Thank you! If I will add this dependency to my library, can I use it for example with spring + Netty?  I want to make a universal solution so that you can use the client both with spring and without spring.

**Comment by kptfh** [comment]
**feign-reactor-web** based on Spring WebClient (based on Netty)

**Comment by kptfh** [comment]
So there are 3 implementations of reactive feign. You may choose one that fits you best

**Comment by hurek** [comment]
Hmm. In the case of creating a library, I probably will have to write several implementations - for spring and for applications that do not use spring? Sorry, this is my first library xD

**Comment by kptfh** [comment]
correct. 
create core module and separate module for each implementation
I use this approach in reactive feign :)
