### ISSUE TITLE
how to set connection timeout reactivefeignclient by clientname?

### ISSUE THREAD

**Issue by gantulgao** [Playtika/feign-reactive#406]
It's given error connection time out?

**Comment by 4duytran** [comment]
Hello, i got too the readtimeout exception from Reactive Feign Client. can i know how to set the read timeout pls ? 
Thanks

**Comment by M00n1ight** [comment]
> Hello, i got too the readtimeout exception from Reactive Feign Client. can i know how to set the read timeout pls ? Thanks

Hello @4duytran. Try to create your client by the configuration class. I think at the moment this is the only way to successfully add a read timeout.
Example:
```
@Configuration
public class ClientConfig {

    @Value("${client-url}")
    private String clientUrl;
    @Value("${client-read-timeout}")
    private Long readTimeout;

    @Bean("clientWithReadTimeout")
    public MyClient client() {
        return WebReactiveFeign
                .<MyClient>builder()
                .options(
                        new WebReactiveOptions.Builder().setReadTimeoutMillis(readTimeout).build()
                )
                .contract(new ReactiveContract(new SpringMvcContract()))
                .target(
                        MyClient.class,
                        clientUrl
                );
    }
}
```

**Comment by kptfh** [comment]
1. via properties file
    [https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration#applicationproperties-configuration](https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration#applicationproperties-configuration) 
    `options : reactive http client specific options. Check implementation of ReactiveOptions.Builder for each client.`
2. via configuration
    [https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration#configuration-via-configuration-class](https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration#configuration-via-configuration-class)
     `Here is the list of bean classes that will be used by reactive feign client if they declared in configuration class: ReactiveOptions.Builder`
