### ISSUE TITLE
Unnecessary trailing slash for static uri in PublisherClientMethodHandler

### ISSUE THREAD

**Issue by ahingsaka** [Playtika/feign-reactive#408]
The class `reactivefeign.methodhandler.PublisherClientMethodHandler.java` creates a "staticUri" with a trailing slash if there is no query parameter.

At line 86 : 
`staticUri = URI.create(target.url() + requestTemplate.url());`

When requestTemplate.url() is called, it returns a "/" by default. 
Thus the "staticUri" variable gets an unnecessary trailing slash.

Expected : /my/path
Real : /my/path/

**Comment by kptfh** [comment]
fixed in 3.1.2

**Comment by kptfh** [comment]
fixed in 3.1.2
