### ISSUE TITLE
Request parameters with multiple values: CollectionFormat equivalent?

### ISSUE THREAD

**Issue by colemanserious** [Playtika/feign-reactive#412]
Is there an equivalent capability for @CollectionFormat(feign.CollectionFormat.CSV) from feign-core?  

Objective: I have a request parameter dataset to which I pass a list of Strings.  Desired behavior is to get dataset=set1,set2,set3.  I currently obtain dataset=set1&dataset=set2&dataset=set3. 

A lookthrough the source code and AllFeaturesFeign test case didn't turn up a means to accomplish.  Is this a supported use case / configuration for feign-reactive?

**Comment by kptfh** [comment]
Seems we didn't implement support of @CollectionFormat.
Why don't you like this option dataset=set1&dataset=set2&dataset=set3 ?

**Comment by colemanserious** [comment]
Purely a matter of syntax, I'm sure.  Just seeking to send per a prescribed contract.  I recognize that the dataset=set1&dataset=set2&dataset=set3 should be accepted by the receiving party, though I don't yet have an endpoint to integrate with.  Was verifying whether I'd overlooked some alternative in the code base.

**Comment by kptfh** [comment]
fixed in 3.1.5
