### ISSUE TITLE
DataBufferLimitException: Exceeded limit on max bytes to buffer

### ISSUE THREAD

**Issue by haingo-kenshjn** [Playtika/feign-reactive#414]
Hi team,

When i use reactive feign client to get data from large data source, got error Exceeded limit on max bytes to buffer : 262144.
How can i config this number to have larger config.

Thanks.
Hai Ngo, 
```
2021-11-26 08:50:51.769 ERROR 1 --- [tor-tcp-epoll-4] a.w.r.e.AbstractErrorWebExceptionHandler : [3318d136-2]  500 Server Error for HTTP GET "/fc/Matches?IsLive=false"


org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144

	at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:98) ~[spring-core-5.3.9.jar:5.3.9]

	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Error has been observed at the following site(s):
```

**Comment by kptfh** [comment]
https://stackoverflow.com/questions/59735951/databufferlimitexception-exceeded-limit-on-max-bytes-to-buffer-webflux-error

**Comment by baahujain** [comment]
> https://stackoverflow.com/questions/59735951/databufferlimitexception-exceeded-limit-on-max-bytes-to-buffer-webflux-error

@kptfh this solution did not work for me. Is there any known issue with below versions?
Feign reactor version - 3.0.0
spring boot 2.6.3

**Comment by hun-a** [comment]
Hi @baahujain, did you find the solution?

**Comment by hun-a** [comment]
@baahujain, I found the solution.
`WebClientFeignCustomizer` accept `webClientBuilder` in the `WebReactiveFeign`.
So, you should config as below. 

```java
    @Bean
    public WebClientFeignCustomizer customClient() {
        return client -> client.exchangeStrategies(
                ExchangeStrategies.builder()
                        .codecs(codec -> codec.defaultCodecs().maxInMemorySize(-1))
                        .build()
        );
    }
```
