### ISSUE TITLE
A problem about feign-reactor-spring-configuration 

### ISSUE THREAD

**Issue by insistent** [Playtika/feign-reactive#42]
I have several reactive-feign client (@ReactiveFeignClient)  in my project，and they have the same value of the attribute “name”.
When I started my application,it throw  exception:
> The bean 'xxx-service.ReactiveFeignClientSpecification', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.

I checked your code：
>reactivefeign.spring.config.ReactiveFeignClientsRegistrar#registerReactiveFeignClients

I find you use the value of  “name”  to regist spring bean.

Hope to fix it soon!

Tks!

**Comment by kptfh** [comment]
In this approach I follow how Spring is doing with Open feign client.

https://github.com/spring-cloud/spring-cloud-netflix/issues/2751
> We don't support multiple `@FeignClient`s with the same name

But you may always configure 2 clients with same name manually

**Comment by Aloren** [comment]
@kptfh maybe makes sense to document this behavior? what do you think?

**Comment by kptfh** [comment]
@insistent @Aloren Updated documentation and added sample project with example how to resolve this issue

> In cloud mode `name` attribute will be used as eureka application name. 
If you need several feign clients for one eureka application 
you should specify eureka application manually in application.yml for feign client with name 
that differs from eureka application name.
See example in [sample project](https://github.com/kptfh/feign-reactive-sample/blob/master/feign/src/main/resources/application.yml)

**Comment by Dahouo** [comment]
You can use contextId attribute

https://cloud.spring.io/spring-cloud-openfeign/reference/html/ 
>   Using contextId attribute of the @FeignClient annotation in addition to changing the name of the ApplicationContext ensemble, it will override the alias of the client name and it will be used as part of the name of the configuration bean created for that client.
