### ISSUE TITLE
jackson properties not working in feign-reactor-spring-configuration

### ISSUE THREAD

**Issue by haycco** [Playtika/feign-reactive#43]
HI,
configure under

```
# Jackson default output print strategy
spring.jackson.property-naming-strategy=SNAKE_CASE
```
when request **@ReactiveFeignClient** api method response json data not working

**Comment by kptfh** [comment]
Quite strange as basic default feign client relies fully on WebClient in terms of json serialization.  Can you check if it works with Spring WebClient?

**Comment by haycco** [comment]
in the application project configuration with override the WebClient Bean using the spring Autowrited it work, but it will cause another problem.

**Comment by tdanylchuk** [comment]
@haycco please provide all steps how-to-reproduce with code snippets, it will help to determine the issue.

**Comment by kptfh** [comment]
@haycco just added an option to customize WebClient via WebClientCustomizer bean. 
Please check if it solved your issue.
You can inspect tests in this commit https://github.com/Playtika/feign-reactive/commit/b4c846b173ab2c0fe682cf5f2de80df98b17422b

**Comment by haycco** [comment]
Hi, @kptfh 
I using version `1.0.26` custom defined WebClientCustomizer bean, but I can not use default `DefaultWebClient` bean to override it.

`1.0.22` is work ok.

I found the code,
**CustomizableWebClientBuilder.java**
```
...
public WebClient build() {
        Builder builder = WebClient.builder();
        if (this.baseUrl != null) {
            builder = builder.baseUrl(this.baseUrl);
        }
...
```
that builder is alaways call  **WebClient.builder()** it......
it not work by customize,  actually I need to use DefaultWebClient.Builder instead of it

in this commit [b4c846b](https://github.com/Playtika/feign-reactive/commit/b4c846b173ab2c0fe682cf5f2de80df98b17422b)

```
public ReactiveFeignBuilder reactiveFeignBuilder(WebClient webClient) {
		return WebReactiveFeign.builder(webClient);
	}
```
interface have been changed.

the changed, cause I can not working Jackson customize properties in config file
```
# Jackson default output print strategy
spring.jackson.property-naming-strategy=SNAKE_CASE
```

**Comment by haycco** [comment]
@kptfh 
I upload the sample code now!
Please, sample code base on you sample project,  [feign-reactive-sample](https://github.com/haycco/feign-reactive-sample) Readme show more

**Comment by kptfh** [comment]
@haycco Check this commit https://github.com/Playtika/feign-reactive/pull/59/commits/242dcf23136b73f9d438ff5161ef82e1ba716615#diff-cf4a8c60d1c156509421248fe7705d01L59
Expecting it should fix your issue.

**Comment by haycco** [comment]
@kptfh it working right now. so good!
