### ISSUE TITLE
setting some properties under reactive.feign.client.config.default.options completely replace any other option set by Configuration class in @ReactiveFeignClient

### ISSUE THREAD

**Issue by MonDeveloper** [Playtika/feign-reactive#437]
In order to better explain my problem I think a little journey is the best story telling:

## Original Problem
The Spring Reactive WebClient based on Netty does not consider the System Properties to create the potential ProxyProvider.
It has been documented and confirmed by the WebClient Netty team; you can see from this reply by a Spring member: https://github.com/reactor/reactor-netty/issues/887#issuecomment-549439355
IMHO, I can't see any valid reason to introduce a so HUGE broken compatibility, anyway....

## Resolution
We added a custom configuration class into the @ReactiveFeignClient attribute on the feign client. This configuration class registered a Bean to build a **WebClientFeignCustomizer** (simplified code):
```java
    @Bean
    public WebClientFeignCustomizer webClientCustomizer() {
            return webClientBuilder -> {
                val httpClient = HttpClient.create().proxyWithSystemProperties();
                val connector = new ReactorClientHttpConnector(httpClient);
                webClientBuilder.clientConnector(connector);
            };
    }
```
And once done everything started working like a charm.

## New requirement
after some months we noticed we need to increase the timeouts for some old services so, in order to set those timeouts, we decided to use the property file (`application.yml`) where we added this:
```yaml
reactive:
  feign:
    client:
      config:
        default:
          options:
            connectTimeoutMillis: 10000
            readTimeoutMillis: 60000
            writeTimeoutMillis: 60000
```
The timeouts were correctly applied and into the development envrironment (with no proxy) everything work fine.

## Current PROBLEM:
Unfortunately once we set the timeouts into the `application.yml`, in the other environments (were we have to use a proxy to reach the services) the proxy problem reappeared.
It seems the configuration class by code is completely ignored once the key `reactive.feign.client.config.default.options` is present within the `application.yml` file.
Our expectation was a sort of merge.

## Workaround:
Removing the `reactive.feign.client.config.default.options` key from the `application.yml` everything is back to work.

## Question is:
There is somthing we did wrong? There is a way to have both timeouts configuration into the `application.yml` and configuration class with Beans into the code?

**Comment by kptfh** [comment]
Properties in yaml file have higher priority then configuration bean.
Try to remove yaml and configure timeouts in bean

**Comment by kptfh** [comment]
Have you tried this approach?
