### ISSUE TITLE
Multipart support along with SpringMvcContract 

### ISSUE THREAD

**Issue by mnbattaglia** [Playtika/feign-reactive#446]
Hi! I'm using feign-reactive to call a service that receives a multipart by using Spring annotations like this:

`    @PostMapping(value = "/test",
        consumes = MULTIPART_FORM_DATA_VALUE,
        produces = APPLICATION_JSON_VALUE)     
    Mono<Result> testMultipart(
        @RequestPart("name") Mono<Part> part);
`
In order to get Spring annotations working we are setting the corresponding contract to our builder:

`.contract(new SpringMvcContract())`

The problem I'm getting is that parts are not being sent in the body, but as query parameters instead. 

`/test?part=someValue`

In order to track the issue down, I checked [this multipart support PR](https://github.com/Playtika/feign-reactive/pull/184/commits/310f54a6e5d0a629022eae1aff0b63d6d8f8851f#) and mimic what you are doing in tests. I declared the client by using Feign annotations (@RequestLine, @Headers, etc.) instead of Spring ones and not setting the Spring contract. In that case, this actually works.

I tried several ways to send the Content-Type header so the framework realizes this is a multipart form, but without success: 
- consumes/produces in the PostMapping Spring annotation
- headers in the PostMapping Spring annotation

I even tried by using a request interceptor and adding the header. But in any case the framework recognizes this request as multipart and always appends the parts as query parameters.

The thing is, I cannot get both ways working together (Spring + Feign annotations). That forces me to define different clients with different configuration just because multipart are not supported with Spring contract. Is there any workaround or plans to support this?

**Comment by lukaszozimek** [comment]
+1 I am facing a similar issue.

**Comment by agaita** [comment]
+1 Would be awesome if we could support this

**Comment by kptfh** [comment]
Hi @mnbattaglia
Can you check this pr [https://github.com/Playtika/feign-reactive/pull/447](https://github.com/Playtika/feign-reactive/pull/447) ?
Just ported test that you mentioned previously to Spring annotations (SpringMvcContract)
What's wrong with it except that it doesn't not support RequestPart annotation?

**Comment by kptfh** [comment]
Apdated with @PathVariable parameter.  Works as well

**Comment by kptfh** [comment]
try the fix in 3.2.1

**Comment by kptfh** [comment]
https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-mvc-test/src/test/java/reactivefeign/spring/mvc/MultiPartTest.java#L146

**Comment by mnbattaglia** [comment]
Wow! That's amazing @kptfh ! Will definitely test it! Thanks a lot
