### ISSUE TITLE
Cross-service invocation not support  @RequestParam

### ISSUE THREAD

**Issue by sunshine7690** [Playtika/feign-reactive#45]
@GetMapping("/test")
    Mono<UserVo> getUserByThirdpart(@RequestParam(value="p") String p, @RequestParam(value="m") String m);

**Comment by kongh** [comment]
I clone your sample project : https://github.com/kptfh/feign-reactive-sample.git

In WebFluxApplication add some methods:

@GetMapping("/greeting2/{id}")
    public Mono<String> greeting(@PathVariable(value = "id") Long id) {
        String idInEureka = eurekaClient.getApplication(appName).getInstances().get(0).getId();
        return Mono.just(String.format("Hello from '%s'!", idInEureka));
    }

    @GetMapping("/greeting3")
    public Mono<String> greeting3(@RequestParam(value = "id") Long id) {
        String idInEureka = eurekaClient.getApplication(appName).getInstances().get(0).getId();
        return Mono.just(String.format("Hello from '%s'!", idInEureka));
    }

    @GetMapping("/greeting4")
    public Mono<String> greeting4(@RequestHeader(value = "id") Long id) {
        String idInEureka = eurekaClient.getApplication(appName).getInstances().get(0).getId();
        return Mono.just(String.format("Hello from '%s'!", idInEureka));
    }

    @PostMapping("/greeting5")
    public Mono<String> greeting5(@RequestBody User user) {
        String idInEureka = eurekaClient.getApplication(appName).getInstances().get(0).getId();
        return Mono.just(String.format("Hello from '%s'!", idInEureka));
    }

In GreetingRactive class:

@ReactiveFeignClient(name = "web-flux-app")
public interface GreetingReactive {

    @GetMapping("/greeting")
    Mono<String> greeting();

    @GetMapping("/greeting2/{id}")
    Mono<String> greeting2(@PathVariable(value = "id") Long id);

    @GetMapping("/greeting3")
    Mono<String> greeting3(@RequestParam(value = "id") Long id);

    @GetMapping("/greeting4")
    Mono<String> greeting4(@RequestHeader(value = "id") Long id);

    @PostMapping("/greeting5")
    Mono<String> greeting5(@RequestBody User user);

Some problem with annotaion @RequestParam, the error is 

There was an unexpected error (type=Internal Server Error, status=500).
GreetingReactive#greeting3(Long) failed and no fallback available.

After change @RequestParam(value = "id", required= false), this method passed.

Please make sure this problem.


And the sample project (https://github.com/kptfh/feign-reactive-sample.git ) upgrade 
<feign-reactor.version>1.0.22</feign-reactor.version>

 Load balancer does not contain an instance for the service 192.168.127.108

Feign cannot invoke remote service.

**Comment by kptfh** [comment]
@kongh Just added endpoint with request parameter. You can check it.
Added `(exclude = ReactiveLoadBalancerAutoConfiguration.class)` 
as after 2.1.0 Spring added LoadBalancerExchangeFilterFunction and it had broken reactive feign LB logic. Will think how to manage it.

**Comment by kongh** [comment]
@kptfh Got it， 3ks. Hope you can fix it later. And can i use "feign-reactive" in production enviroment, I am planing to develop a full stack cloud reactive application. Can you give me a suggestion ?

**Comment by kptfh** [comment]
Didn't find good solution how to avoid conflict with ReactiveLoadBalancerAutoConfiguration.class, so you still need to exclude it
