### ISSUE TITLE
Can't customize the ObjectMapper used by feign-reactor-webclient

### ISSUE THREAD

**Issue by rossinimartins** [Playtika/feign-reactive#49]
I want to add a custom module to the ObjectMapper used by **feign-reactor-webclient**.

Things that I have tried and none of then worked:

- Create a `@Bean` of the Module
- Create a `@Bean` of type `WebClientCustomizer`

The alternatives above works when I inject the WebClient directly, but not when I use a `@ReactiveFeignClient` interface.

I think it may be happening because, according to the javadoc in `ReactiveFeignContext`, "It creates a Spring ApplicationContext per client name", wich, apparently overrides the application context where I am injecting the beans that I mentioned above.

There is any way I can customize the ObjectMapper used by **feign-reactor-webclient**? Maybe an undocumented one that I could not find? Or this is the intended behaviour?

I'm using **feign-reactor-webclient** and **feign-reactor-spring-configuration** with Spring Boot 2.1.3.RELEASE.

**Comment by kptfh** [comment]
just merged fix with 2 options how to configure WebClient:
- custom WebClient bean
- WebClientCustomizer bean
Plan to release it on Monday 03/11/2019
