### ISSUE TITLE
@PathVariable does not insert the value in the request

### ISSUE THREAD

**Issue by dougnob** [Playtika/feign-reactive#506]
Hi All,

I have recently replaced spring-cloud-openfeign with feign-reactive to call an external API. One of the HTTP request to this external API includes a parameter in the following format **_?filter=Company:The%20Greatest%20Company_**. I have noticed that the presence of the colon seems to prevent the insertion of the value "The Greatest Company" when using @PathVariable. I was not getting the same behavior when using spring-cloud-openfeign. I am using feign-reactive 3.2.6.

Here is the method signature:
```
@GetMapping("/Invoices?filter=Company:${companyName}")
public Flux<Invoice> findInvoicesByCompany(@PathVariable("companyName") String company);
```

Here is the logged request:
`--->GET https://API_URL/Invoices?filter=Company%3A%24%7BcompanyName%7D HTTP/1.1`

I am not sure if this issue comes from feign-reactive or an underlying library, any guidance would be appreciated.

Thanks in advance,

**Comment by skaba** [comment]
That's a @RequestParam not a @PathVariable

**Comment by dougnob** [comment]
Hi @skaba, thanks for your reply.

Technically speaking, yes...
But I don't want the whole filter parameterized, just the companyName. Is the change of behavior from spring-cloud-openfeign intentional? I did not have this issue when using it.

**Comment by kptfh** [comment]
please check 3.2.10
