### ISSUE TITLE
All requests returns 503

### ISSUE THREAD

**Issue by andrei-playtika** [Playtika/feign-reactive#51]
Starting from version 1.0.21, any request with reactive feign client returns response status 503.
with message "Load balancer does not contain an instance for the service 192.168.127.108"
(same requests worked fine with 1.0.20)

**Comment by kptfh** [comment]
As workaround you need to exclude `ReactiveLoadBalancerAutoConfiguration` from auto-configuration.
Starting from 2.1.0 Spring added load balancer for WebClient and it breaks current implementation. Will think how to appropriately mange it.

**Comment by kptfh** [comment]
Didn't find good solution. Will update documentation to exclude ReactiveLoadBalancerAutoConfiguration
