### ISSUE TITLE
Cut trailing slash `/` even if it's not unncessary

### ISSUE THREAD

**Issue by meowpunch** [Playtika/feign-reactive#514]
While updating, I got issue because it cut the trailing slash even though using the trailing slash intentionally.

Basically, my API server's endpoint is configured as
`/users/{userId}/dogs/` not `/users/{userId}/dogs` when fetching the overviews of dogs collection without params.

However, with this update `PublisherClientMethodHandler` cut the trailing endpoint. So, my feign client got 404 Not found (URL).

I expected feign client should request to url with trailing slash if it's configured with trailing slash.

when: `@RequestLine("GET /users/{userId}/dogs/")`
expected: `/users/{userId}/dogs/`
real: `/users/{userId}/dogs`

**Comment by kptfh** [comment]
please check 3.2.10
