### ISSUE TITLE
This builder should return same type of object on methods, otherwhise there is no way to keep building params related to the object like username, password....

### ISSUE THREAD

**Issue by AlexMartinezVila** [Playtika/feign-reactive#515]
https://github.com/PlaytikaOSS/feign-reactive/blob/020c37132e6c00d66ee2dd44e72d9f56e5626744/feign-reactor-webclient/src/main/java/reactivefeign/webclient/WebReactiveOptions.java#L174

**Comment by kptfh** [comment]
please check 3.2.10
