### ISSUE TITLE
How to solve the problem of repeatedly registering beans？

### ISSUE THREAD

**Issue by baiyifengyun** [Playtika/feign-reactive#518]
Description:

The bean 'medical-product-service.ReactiveFeignClientSpecification' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by kptfh** [comment]
> You should specify `name` attribute in this annotation. Feign client bean will be registered with the name of `name + "ReactiveFeignClient"`
if you had not specified `qualifier` attribute.

In case if you want to use the same client (interface) with different configs you should provide different qualifier attribute in ReactiveFeignClient annotation

**Comment by xxscloud5722** [comment]
![image](https://github.com/PlaytikaOSS/feign-reactive/assets/63572603/24d45c2e-5c14-4377-9f0b-478109d87bea)

![image](https://github.com/PlaytikaOSS/feign-reactive/assets/63572603/9a708c5f-5d47-4f73-8a0a-394f17a49758)

Is it ineffective?
