### ISSUE TITLE
WebClient request metrics is useless

### ISSUE THREAD

**Issue by Delorien84** [Playtika/feign-reactive#52]
Hi,
 we use the library for a lot of our services and it working quite well. 

We have detect problem ugprading to Spring Bott 2.1. Since Spring Boot 2.1, the framework expose WebClient Metrics (see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-metrics-http-clients). To working the metrics correctly it is required to use `template` uri. Eg. to use `webClient.get().uri("/users/{id}", 1)`. But current implementation construct full `URI` from method `@RequestLine` and then call eg. `webClient.get().uri("/users/1")`. 

This causing to have metrics for every URL parameters and effectively they are useless.

**Comment by kptfh** [comment]
Unfortunately there is no possibility to use 'template' via webClient.get().uri("/users/{id}", 1). 
Will consider an option to add reactive feign's own metrics.
