### ISSUE TITLE
3.2.6 toFuture have no response (BLOCKED)

### ISSUE THREAD

**Issue by zt9788** [Playtika/feign-reactive#527]
Use the 3.2.1 it is OK,but when I use de 3.2.6(spring gateway(webflux)2.7.4) the programe no response in all thread
```
@ReactiveFeignClient(name = "test",url = "....")
public interface TestFeign {
    @PostMapping(value = "/test", consumes = MediaType.APPLICATION_JSON_VALUE)
    Mono<String> test(@RequestBody Test request);
}


@GetMapping("/system/healty")
    public String healty(){
        CompletableFuture<String> voidCompletableFuture  = TestFeign.test(request).toFuture();
        responseData = voidCompletableFuture.get(2000,TimeUnit.SECONDS); //in 3.2.1 it is OK,but 3.2.6 BLOCKED
        return "....";
    }
```

**Comment by kptfh** [comment]
Can't reproduce. On the latest version it works as expected.

**Comment by vladimir-narkevich-idf** [comment]
@kptfh hi, i am having a similar issue, i have written a simple rest  controller that makes a call to an external service with feign client. When i enable retry policy i get a successfully response from feign client but my rest controller gets blocked for about 2 minutes if I disable retry policy I receive response without block

**Comment by vladimir-narkevich-idf** [comment]
@kptfh  Code look like this `@ReactiveFeignClient(name = "test",url = "....")
public interface TestFeign {
    @PostMapping(value = "/test", consumes = MediaType.APPLICATION_JSON_VALUE)
    Mono<String> test(@RequestBody Test request);
}

@Configuration
@EnableReactiveFeignClients(
  clients = [
    TestFeign::class
  ]
)
class ConnectorConfig {

  @Bean
  fun reactiveOptions(httpSettings: HttpSettings): ReactiveOptions =
    WebReactiveOptions.Builder()
      .setReadTimeoutMillis(Duration.parse(httpSettings.readTimeout).toMillis())
      .setWriteTimeoutMillis(Duration.parse(httpSettings.writeTimeout).toMillis())
      .setConnectTimeoutMillis(Duration.parse(httpSettings.connectTimeout).toMillis())
      .build()

  @Bean
  fun reactiveRetryPolicy(retryPolicySettings: RetryPolicySettings): ReactiveRetryPolicy =
    FilteredReactiveRetryPolicy.notRetryOn(
      BasicReactiveRetryPolicy.retryWithBackoff(
        retryPolicySettings.maxAttempts,
        Duration.parse(retryPolicySettings.duration).toMillis()
      ),
      JsonMappingException::class.java,
      JsonParseException::class.java,
      FeignException.UnsupportedMediaType::class.java,
      FeignException.MethodNotAllowed::class.java
    )
}

@GetMapping("/system/healty")
    fun healty() = TestFeign.test(request)
   `

**Comment by KamaniAman** [comment]
@zt9788 is it resolved?

@kptfh I am facing this issue in version 3.3.0, If used `.toFuture().get()` then it is not receiving API response. 
I have also tried using `.block()` but it is throwing error `block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-4`

**Comment by zt9788** [comment]
> @zt9788 is it resolved?
> 
> @kptfh I am facing this issue in version 3.3.0, If used `.toFuture().get()` then it is not receiving API response. I have also tried using `.block()` but it is throwing error `block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-4`

I am not try the new version yet. and use webclient instead feign-reactive
