### ISSUE TITLE
One service creates multiple ReactiveFeignClients?

### ISSUE THREAD

**Issue by baiyifengyun** [Playtika/feign-reactive#531]
How to use multiple ReactiveFeignClients to connect to the same service?

**Comment by kptfh** [comment]
Are you going to use auto-configuration or manual configuration of feign clients?

**Comment by kptfh** [comment]
> You should specify `name` attribute in this annotation. Feign client bean will be registered with the name of `name + "ReactiveFeignClient"`
if you had not specified `qualifier` attribute.

In case if you want to use the same client (interface) with different configs you should provide different qualifier attribute in ReactiveFeignClient annotation
