### ISSUE TITLE
Is Feign-reactive SOAP Complaint?

### ISSUE THREAD

**Issue by pavithra10391** [Playtika/feign-reactive#533]
Are we able to make SOAP call via feign-reactive and get Mono/Flux response? No Proper documentation found for the library, please improve documentation

**Comment by pavithra10391** [comment]
Any update?

**Comment by RavindarThatipelly** [comment]
Could you provide update for this doubt whether Fiegn Reactive support SOAP calls or not?

**Comment by kptfh** [comment]
Feign client won't provide you any additional benefit for SOAP compared to direct WebClient usage.
