### ISSUE TITLE
Can I use feign-reactive while using Spring MVC as the main?

### ISSUE THREAD

**Issue by wonsik-ha** [Playtika/feign-reactive#555]

**Comment by mnbattaglia** [comment]
Absolutely. We are using it without issues. You just need to block() your calls

**Comment by kptfh** [comment]
Yes. 
But you won't get a lot of benefits compared to blocking version (Open Feign).
The only advantage  here is the ability to process response asynchronously (in reactor pool of threads).

**Comment by mnbattaglia** [comment]
Exactly. In our case, we are using a common interface for either implementing the service and also to provide a client, and we are using always response reactive types (Mono/Flux). So even if we implement the service with MVC, as we are returning reactive types, we are using Reactive Feign to provide a client that works with those types (I think that open feign still doesn't support reactive types)
