### ISSUE TITLE
Is it possible to create cloud enabled ReactiveFeignClients manually?

### ISSUE THREAD

**Issue by stewartgdev** [Playtika/feign-reactive#558]
I am attempting to create many clients from a single interface but with different target using eureka at runtime to perform the address translation. I have set properties reactive.feign.cloud.enabled: true & reactive.feign.loadbalancer.enabled: true and can see those beans in the ReactiveFeignClientsConfiguration class being instantiated however I cannot create the clients using the reactiveFeignCloudBuilder.

Any time I try to create the clients or import that builder, I either get "CloudReactiveFeign.Builder expected" as a WebClient.Builder is passed into the ReactiveFeignLoadBalancerConfigurator or the client which is created does not have the LoadBalancer set on the client and so cannot resolve the name to an IP/URL.

If possible could you please provide an example with configuration showing how this can be done?

**Comment by kptfh** [comment]
Sure. Here is the test that covers your case
[LoadBalancingReactiveHttpClientTest](https://github.com/PlaytikaOSS/feign-reactive/blob/develop/feign-reactor-cloud/src/test/java/reactivefeign/cloud2/LoadBalancingReactiveHttpClientTest.java)

**Comment by stewartgdev** [comment]
Thanks for responding, it turned out that my issue was that when creating the client with a URL but not a name, the code was assuming that it did not need to resolve the URL via eureka. By adding both a name and URL, it correctly started performed a lookup on the URL and resolved correctly. Thanks for your time looking into my issue.
