### ISSUE TITLE
WebReactiveOptions support for maxIdleTime and maxLifeTime

### ISSUE THREAD

**Issue by mnbattaglia** [Playtika/feign-reactive#559]
We recently found some issues where, after being idle for a while, our next request throws a `WebClientRequestException: readAddress(..) failed: Connection reset by peer` exception. It seems that the connection pool is trying to reuse a connection already closed by the server but the pool is not aware of it. There could be several reasons for it, but the suggestion everywhere is to set the maxIdleTime to the pool so those idle connections are discarded before being disconnected from the server.

This configuration happens at the ConnectionProvider. There are some netty system properties that can be set as default values, but we want to set this programatically. There is no way to configure this in Feign Reactive if we use the default implementation of the ClientHttpConnector created by NettyClientHttpConnectorBuilder. There are other parameters that can be set to the ConnectionProvider via WebReactiveOptions (eg: maxConnections, pendingAcquireMaxCount, etc.) but maxIdleTime and maxLifeTime are missing there.

As a workaround, we can provide our own implementation of a HttpClient with that configured and pass it to the WebReactiveFeign.Builder when creating our instance. So, we can just copy/paste the whole NettyClientHttpConnectorBuilder.buildNettyClientHttpConnector() logic (HttpClient instantiation part) and add the needed configuration when ConnectionProvider.Builder is created.

So, ideally, `maxIdleTime` and `maxLifeTime` should be added to WebReactiveOptions and properly set in the NettyClientHttpConnectorBuilder.buildNettyClientHttpConnector so we can configure these properties as there are lot of reports of this error and similar ones. In fact, I think the one reported in #552 can be fixed by setting the maxIdleTime variable.

Thanks and happy to collab!

**Comment by mnbattaglia** [comment]
Please, also consider adding the `metrics` attribute as well

**Comment by jchrobert** [comment]
Might relate to this https://github.com/reactor/reactor-netty/issues/1774

**Comment by mnbattaglia** [comment]
@jchrobert it is related indeed. That's why we need to be able to set those props. via feign configuration

**Comment by mnbattaglia** [comment]
Thanks @kptfh to get this fixed so quickly. When is the release of next version including these changes planned?

**Comment by kptfh** [comment]
next week

**Comment by kptfh** [comment]
please check 3.2.10

**Comment by zBo1997** [comment]
@mnbattaglia Oh~ I'm sorry to raise the question again after a long time has passed regarding this matter，I have also discovered a similar issue . May I ask if you can provide logic of "NettyClientHttpConnectorBuilder.buildNettyClientHttpConnector() "
I will be extremely grateful

**Comment by kptfh** [comment]
Hi.
Feel free to make PR.
