### ISSUE TITLE
Reactive Feign SSL Configuration 

### ISSUE THREAD

**Issue by henriquemt1312** [Playtika/feign-reactive#572]
Hi, I am currently using version 3.2.6 of the feign-reactive library and I am facing a problem with an SSL connection. I am trying to make a request to a third-party application that expects a .pfx certificate. I was able to deal with this situation using Feign Client, as shown in the image below:
![image](https://user-images.githubusercontent.com/78218918/231167486-d132bc13-5593-41a3-922a-89bf7dc970a8.png)

However, I really have no clue how to accomplish the same thing using ReactiveFeign.

**Comment by kptfh** [comment]
In 3.2.10 you can configure client's SslContext
https://github.com/PlaytikaOSS/feign-reactive/blob/develop/feign-reactor-webclient/src/main/java/reactivefeign/webclient/WebReactiveOptions.java#L163
