### ISSUE TITLE
Reactive ReactiveHttpRequestInterceptor

### ISSUE THREAD

**Issue by Delorien84** [Playtika/feign-reactive#60]
Hi,
 I would like to have reactive based `ReactiveHttpRequestInterceptor`. My goal is to add `Authorization` header to all requests using request itnerceptor. I was thinking to do something like. To get `Authorization` data from `Mono` `Context`:

```
WebReactiveFeign
                .<Client>builder(webClientBuilder)
                .decode404()
                .addRequestInterceptor(request -> Mono
                            .subscriberContext()
                            .map(ctx -> ctx
                                    .<String>getOrEmpty("authToken")
                                    .map(authToken -> {
                                        Map<String, List<String>> headers = new LinkedHashMap<>(request.headers());
                                        headers.put("Authorization", List.of(authToken));
                                        return new ReactiveHttpRequest(request.method(), request.uri(), headers, request.body());
                                    })
                                    .orElse(request));)
                .target(Client.class, "http://localhost:8080")
```

Or is there any other recommended approach?

Thanks

**Comment by kptfh** [comment]
You are on the right way. The only alternative is to pass them explicitly as method parameter
[](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-mvc-test/src/test/java/reactivefeign/spring/mvc/allfeatures/AllFeaturesMvc.java#L60)
