### ISSUE TITLE
Blocking Apache HttpClient v3.1

### ISSUE THREAD

**Issue by vivdnp** [Playtika/feign-reactive#61]
Reactive non-blocking client has dependency on blocking Apache HttpClient :)

Moreover, it uses outdated version 3.1, which has known vulnerability - https://www.sourceclear.com/vulnerability-database/libraries/HttpClient/JAVA/MAVEN/lid-110/versions/3.1

As I see from source code - the only place to use Apache HttpClient is resolving text message from http status code

Expected outcome - please remove unnecessary dependency

**Comment by kptfh** [comment]
It's open source project. You are welcomed to create pull request that fix this issue.
BTW. There is also dependency on __open feign__ project that is also blocking.
The only place where we use Apache HttpClient is status handler based on feign ErrorDecoder
