### ISSUE TITLE
feign-reactor-java11: make "transfer-encoding: chunked" optional

### ISSUE THREAD

**Issue by martin-mfg** [Playtika/feign-reactive#610]
When using feign-reactor-java11, the generated HTTP requests contain the header "transfer-encoding: chunked". Since this is a problem for some servers, I suggest adding an option to disable chunked encoding. Or maybe disabling it by default.

The relevant line in feign-reactor-java11is [this](https://github.com/PlaytikaOSS/feign-reactive/blob/baba570b5039c649d5487883f3db1e183026773a/feign-reactor-java11/src/main/java/reactivefeign/java11/client/Java11ReactiveHttpClient.java#L239C52-L239C76). There, `fromPublisher` is called without a `contentLength` argument. If `contentLength` would be set, the "transfer-encoding" header would not be inserted.

Btw, thanks for your work on this great library. :)

**Comment by kptfh** [comment]
It's tricky to calculate contentLength in general for reactive approach.
From my perspective it's issue of your servers.
Reopen issue please if you would like to introduce PR.
