### ISSUE TITLE
change default jackson to gson

### ISSUE THREAD

**Issue by dnjat** [Playtika/feign-reactive#618]
using feign-reactive,reactor.netty.http.client  http.codec.json default jackson, can support gson?

**Comment by rhys-saldanha** [comment]
Reactive Spring doesn't support GSON. You can read more here: https://github.com/spring-projects/spring-framework/issues/27131

The issue comments do mention a work-around where you can define a custom encoder/decoder which uses GSON and will work in "most" cases. I can see that `WebReactiveFeign.builder` can take in a `WebClientFeignCustomizer`, which should allow you to pass in a customiser that configures WebClient to use your custom encoder/decoder.
