### ISSUE TITLE
Problem with feign-reactor-cloud without having Ribbon

### ISSUE THREAD

**Issue by piotrowskialek** [Playtika/feign-reactive#62]
Is it possible (and how if it is) to use a reactive feign client WITH Hystrix but WITHOUT Ribbon (smart load balancer)? 

What I'm trying to achive is just calling an address I've provided in (reactive) feign client in 'url' property and provide a fallback or fallback factory to be called when feign fails. I would also like to use Hystrix Circuit Breaker pattern with HystrixCommandKey and HystrixCommandMetrics. Because of that I've decided to use feign-reactor-cloud project as well as feign-reactor-webclient and feign-reactor-core.

I'm able to do that with a simple, synchronous feign client but i can't make a call with a reactive one after I've added feign-reactor-cloud to my project.

Do you know how to exclude Ribbon configuration or provide a something like a NoOp Ribbon?
Now when I'm trying to call an API through the ReactiveFeignClient I'm getting an exception: [com.netflix.client.ClientException: Load balancer does not have available server for client: reactive-feign-client] which is thrown most likely because my application (or more precisely Ribbon client) don't know the address of Ribbon server - but I don't have one and I don't want to have it.
Cheers

**Comment by kptfh** [comment]
Hi. Do you use Spring auto-configuration  or configure feign client manually? 
1)For manual configuration Ribbon is disabled by default.
2)For auto-configuration there is an option to specify static list of servers for Ribbon load balancer. You can check this test for [ribbon.listOfServers](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-cloud-test/src/test/java/reactivefeign/spring/config/AutoConfigurationTest.java#L58)

**Comment by kptfh** [comment]
BTW, have you checked [Spring Auto Configuration docs](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-spring-configuration/README.md) ?

There is setting that should fit your needs the best 
> set reactive.feign.ribbon.enabled to false to disable ribbon configuration for all clients

**Comment by piotrowskialek** [comment]
That's exactly what I wanted to achieve :) thank you so much
