### ISSUE TITLE
Query parameters encoding

### ISSUE THREAD

**Issue by KuliginStepan** [Playtika/feign-reactive#73]
Hi, thanks for fix #63, but I am faced with an issue when I have a URL like `http://host/search?filter=workers=in=("123")` it should be encoded to `http://host/search?filter=workers%3Din%3D(%22123%22)` but now it's encoded to `http://host/search?filter=workers=in=(%22123%22)`

To fix this you can use `UriUtils.encode()` instead of `UriUtils.queryEncode()`

**Comment by kptfh** [comment]
Thank you a lot for this issue. Fixed and will be released in 2.0.1
