### ISSUE TITLE
Cloudless client configuration

### ISSUE THREAD

**Issue by KuliginStepan** [Playtika/feign-reactive#74]
### Case
I have a project with reactive feign clients. Some clients need to be configured in a cloud mode, so I put `feign-reactor-cloud` in the classpath. But several clients are external APIs, so these clients need to be configured in cloudless mode.
###  Expected behavior
In openfeign this case solved by `url` attribute in `@FeignClient`. If `url` is present then load balancer doesn't apply to this client
### Actual behavior
In reactivefeign load balancer applied to these clients
if I use `reactive.feign.ribbon.enabled` and `reactive.feign.hystrix.enabled` it disables ribbon and hystrix globally.

**Comment by kptfh** [comment]
Currently there is an option to specify [static host in ribbon.listOfServers](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-cloud-test/src/test/java/reactivefeign/spring/config/AutoConfigurationTest.java#L57)

**Comment by kptfh** [comment]
resolved in 1.0.43 the same way as in OpenFeign
> In openfeign this case solved by url attribute in @FeignClient. If url is present then load balancer doesn't apply to this client
