### ISSUE TITLE
Too many metrics generated when using Path Variables

### ISSUE THREAD

**Issue by andrei-playtika** [Playtika/feign-reactive#77]
Using requests with PathVariables in reactive feign client 
(ex.:     @GetMapping("/{cropId}/summary"))
leads to generating metrics for each request separately 
(ex: /2339501/summary.snapshot.50thPercentile, /2339502/summary.snapshot.50thPercentile, etc.)
Then it finishes with this Warning:
WARN org.springframework.boot.actuate.autoconfigure.metrics.OnlyOnceLoggingDenyMeterFilter - Reached the maximum number of URI tags for 'http.client.requests'. Are you using 'uriVariables'?

Same requests didn't generate separate metrics in synchronous feign client.

**Comment by kptfh** [comment]
Reactive Feign client has it's own Micrometer metrics. [set reactive.feign.metrics.enabled to true to enable default Micrometer logger. Also make sure that you added actual Micrometer implementation module into your project dependency](https://github.com/Playtika/feign-reactive/tree/develop/feign-reactor-spring-configuration)

**Comment by andrei-playtika** [comment]
The problem is not in that there are no metrics. The problem is that there are too many metrics: Reactive feign client generates separate metrics for same requests, for each PathVariable. In that case, if request contains UserId in path variables, Reactive feign will generate thousands of same metrics.
seting reactive.feign.metrics.enabled to true/false doesn't change situation

**Comment by kptfh** [comment]
To many metrics generates Spring WebClient as reactor feign doesn't use it in form of template with substitutions. You need to turn off WebClient metrics and turn on reactive feign metrics.
Please check [MetricsTest](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-core/src/test/java/reactivefeign/MetricsTest.java).

**Comment by andrei-playtika** [comment]
Thanks, it helped:
management.metrics.enable.http.client.requests: false
reactive.feign.metrics.enabled: true

Please, add this to documentation.
