### ISSUE TITLE
Seems return directly, when 204 returned

### ISSUE THREAD

**Issue by xtestw** [Playtika/feign-reactive#78]
RT,

**Comment by xtestw** [comment]
`public Mono<Object> getStaticAds(AdParam adParam) {
    return remoteService.getStaticAds(adParam.getOriginMap())
        .doOnNext(item->{
          System.out.println(item);
        })
        .onErrorReturn(AdResult.genNoneAdResult());
  }
`
when remoteService return 204 code, donext will not execute and the process complete.

**Comment by tdanylchuk** [comment]
please format properly your case&question

**Comment by kptfh** [comment]
@xtestw 204 status code stands for successful  response with empty body thus `doOnNext` will be never called and `onErrorReturn` as well.

**Comment by xtestw** [comment]
> please format properly your case&question

sorry for that , and the code is as follow:
`public Mono<Object> getStaticAds(AdParam adParam) {
                  return remoteService.getStaticAds(adParam.getOriginMap())
                                                      .doOnNext(item->{ System.out.println(item); })
                                                      .onErrorReturn(AdResult.genNoneAdResult()); 
}`

**Comment by xtestw** [comment]
> @xtestw 204 status code stands for successful response with empty body thus `doOnNext` will be never called and `onErrorReturn` as well.

i see... Mono.empty() just like a hole 2333, and i use ```defaultIfEmpty``` to solve it. it's really right to return empty when 204. thanks for your response.
