### ISSUE TITLE
Zipkinn/Sleuth + ReactiveFeign

### ISSUE THREAD

**Issue by mrdextr** [Playtika/feign-reactive#79]
I am currently facing the problem of getting different TraceIDs when forwarding requests with ReactiveFeign. There is a new TraceID every time the request gets through my gateway, which I use to check if credentials are valid.

Ran into this on research:
https://stackoverflow.com/questions/48211360/how-to-implement-sleuth-tracing-with-feign-builder

So I wondered if this is also possible with ReactiveFeign? I can't get it to work. Maybe you could point me in the right direction.

Thanks in advance for the answer!

**Comment by haycco** [comment]
zipkin/sleuth support web client, you can config  `spring.sleuth.web.client.enabled=true`

**Comment by kptfh** [comment]
Added [test](https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-test/feign-reactor-spring-configuration-cloud-test/src/test/java/reactivefeign/spring/config/SleuthTest.java) to prove that ReactiveFeignClient over WebClient supports Sleuth. The only detail you should pay attention that WebClient should be autoconfigured by Spring. Only in this case it will be correctly instrumented.
