### ISSUE TITLE
How to configure webclient  keepalive and connection pool ?

### ISSUE THREAD

**Issue by tdwu** [Playtika/feign-reactive#80]
modify   CustomizableWebClientBuilder  but no work.

Function<HttpClient, HttpClient> mapper = client ->
                client.tcpConfiguration(c ->
                        c.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, webOptions.getConnectTimeoutMillis().intValue())
                                .option(ChannelOption.SO_KEEPALIVE,true)
                                .option(ChannelOption.TCP_NODELAY, true)
                                .doOnConnected(conn -> {
                                    conn.addHandlerLast(new ReadTimeoutHandler(
                                            webOptions.getReadTimeoutMillis(), TimeUnit.MILLISECONDS));
                                    conn.addHandlerLast(new WriteTimeoutHandler(
                                            webOptions.getWriteTimeoutMillis(), TimeUnit.MILLISECONDS));
                                    log.info("doOnConnected：" + conn.hashCode());
                                }).doOnDisconnected(connection -> {
                            // [Q1 ]after response closed 
                            log.info("doOnDisconnected：" + connection.hashCode());
                        })).keepAlive(true) // [Q2]http keep alive no work
.chunkedTransfer(false);
        return new ReactorClientHttpConnector(reactorResourceFactory, mapper);

   public ReactorResourceFactory resourceFactory() {
        ReactorResourceFactory factory = new ReactorResourceFactory();
        factory.setUseGlobalResources(false);
        factory.setConnectionProvider(ConnectionProvider.fixed("cpool", 10));
        factory.setLoopResources(LoopResources.create("cpooll", 4, true));
        return factory;
    }

**Comment by tdanylchuk** [comment]
please properly format your question and give some details what you want to achieve.

**Comment by tdwu** [comment]
Webclient configuration pool in My Test Code. Happened doOnDisconnected  after response decoder.
Grab the package through wirechark. No  TCP disconnected .
Maybe it just a state changed.

Forgive my poor English。
